### ISSUE TITLE
Please support http proxy

### ISSUE THREAD

**Issue by allenxiang** [prometheus-msteams/prometheus-msteams#101]
Many companies do not allow direct internet access and services have to use internal http/https proxy to reach external urls like MS Teams webhooks. Please add a feature to support http proxy. Thanks.

**Comment by bzon** [comment]
This should work automatically. Can you try setting up `HTTP_PROXY` or `HTTPS_PROXY` environment variables?

**Comment by allenxiang** [comment]
Tested with the environment variables and it worked! Thanks a lot for your help!
