### ISSUE TITLE
Failed sending to webhook URL. i/o Timeout[BUG]

### ISSUE THREAD

**Issue by ragemoody** [prometheus-msteams/prometheus-msteams#105]
**Describe the bug**
Curling the prom-alert.json to the prometheus-msteams container results in the following error message:

Failed sending to webhook url https://outlook.office.com/webhook/xxx. Got the error: Post https://outlook.office.com/webhook/xxx: dial tcp: lookup outlook.office.com on 127.0.0.11:53: read udp 127.0.0.1:54049->127.0.0.11:53: i/o timeout

Additionaly the log of my alertmanager container says the following:

level=error ts=2020-03-14T16:41:39.021Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="Post http://promteams:2000/alert_channel: context deadline exceeded" context_err="context deadline exceeded"
level=error ts=2020-03-14T16:41:39.021Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Post http://promteams:2000/alert_channel: context deadline exceeded"

**Version**
I am running everything in containers on a single host. Prometheus-msteams version is 1.1.4

**Comment by bzon** [comment]
I assume https://outlook.office.com/webhook/xxx is not your real webhook url? This looks like a DNS issue or internet connectivity issue.

Can you also try using the latest release version? Take note that the docker repo has also been changed.

If the issue still persist, I want you to simply test your container network by manually **curl**-ing your webhook url.

**Comment by ragemoody** [comment]
Yea i edited out the part after "webhook/" vor overview reasons.
What i just did:

- updated to latest image
- generated a new webhook url and edited the promteams config file
- curl'd the prom-alert.json from my docker host to the webhook-url. This was the outcome:
   
> curl -X POST -d @prom-alert.json https://outlook.office.com/webhook/xxx
Summary or Text is required

- I tried curling from the promteams container to the webhook-url but curl is not installed and so far i wasn't able to install it myself because i'm running into some other errors. Will try to do that now.

**Comment by bzon** [comment]
@ragemoody yep. 

> curled the prom-alert.json from my docker host to the webhook-url. This was the outcome:
> curl -X POST -d @prom-alert.json
> Summary or Text is required

By the way, this command is meant to target the prometheus-msteams server url and not the webhook url.

I will close this issue for now.

**Comment by StephJon** [comment]
I'm having a similar issue, except I'm able to manually curl to the webhook url.

`curl -X POST -d @prom-alert.json 127.0.0.1:2000/alertmanager`

- **output:** http client failed: Post https://lightingaad.webhook.office.com/webhookb2/-redacted-: POST https://lightingaad.webhook.office.com/webhookb2/-redacted- giving up after 4 attempt(s): Post https://lightingaad.webhook.office.com/webhookb2/-redacted-: dial tcp 52.-redacted-: i/o timeout

`curl -X POST -d @test-teams-webhook-msg.json https://lightingaad.webhook.office.com/webhookb2/-redacted-`

- successfully posts a message to the teams channel
- ![image](https://user-images.githubusercontent.com/87027297/124623646-2420af00-de4a-11eb-8b25-ffccfd7c7942.png)

**Comment by Knappek** [comment]
@StephJon it seems like you don't have connectivity from `prometheus-msteams` to MS Teams. Can you elaborate please how `prometheus-msteams` is running? Is it running on Kubernetes, docker, on a linux host etc? What's the network architecture underneath, does it have internet access  etc.?

**Comment by StephJon** [comment]
Prometheus-msteams is running on docker (through snap).
It does have internet access and I'm running behind a corporate proxy.

When initially setting it up, I used the command:
`/snap/bin/docker run -d -p 2000:2000 \`
`    --name="promteams" \`
`    -e TEAMS_INCOMING_WEBHOOK_URL="https://lightingaad.webhook.office.com/webhookb2/-radacted-" \`
`    -e TEAMS_REQUEST_URI=alertmanager \`
`    quay.io/prometheusmsteams/prometheus-msteams`

**Comment by Knappek** [comment]
> Setting localhost and 127.0.0.1 to the no_proxy environment variable fixed the blocking issue, but resulted in the timeout as indicated in my previous comment.
This is odd when I can directly POST to the webhook url.

I don't understand this comment. What is the `blocking issue` and what is `the timeout as indicated in my previous comment`? Why should it be odd to have a different behaviour when calling `localhost` as opposed to a public MS team webhook URL?

Regarding your docker setup, did you consider to [configure Docker to use a proxy server](https://docs.docker.com/network/proxy/)?
