### ISSUE TITLE
Provide linux binary for v1.3.3

### ISSUE THREAD

**Issue by supaflyster** [prometheus-msteams/prometheus-msteams#106]
**Describe the bug**
Hi, Looks like 1.3.3 release has only darwin binary, can you please also release the linux one please?

**Version**
The docker image or release version of prometheus-msteams.
1.3.3

<img width="1024" alt="Screenshot 2020-03-18 at 11 05 18" src="https://user-images.githubusercontent.com/6348312/76949307-9f361d00-6908-11ea-8fe5-4fcc1cccc3f9.png">

Thank you!

**Comment by bzon** [comment]
![Screen Shot 2020-03-19 at 11 20 02 PM](https://user-images.githubusercontent.com/19391568/77120132-5aa99f00-6a38-11ea-9605-a1aa1183c40f.png)

Not sure what happened but it seems that file was corrupted.

**Comment by bzon** [comment]
The Linux binary is now available!
