### ISSUE TITLE
[BUG] helm chart warnings regarding default value for connectors

### ISSUE THREAD

**Issue by despick** [prometheus-msteams/prometheus-msteams#109]
**Describe the bug**
When overriding the connector values helm will issue a warning:
Warning: Merging destination map for chart 'prometheus-msteams'. Overwriting table item 'connectors', with non table value: [map[alertmanager:https://outlook.office.com/xxx] map[alertmanagerApproval:https://outlook.office.com/webhook/yyy]]

**Version**
The docker image or release version of prometheus-msteams.
docker image 1.3.3, helm chart 0.4.4
**To Reproduce**
Override the default connector values when installing the chart.
connectors:
  - alertmanager: https://outlook.office.com/webhook/xxx
  - alertmanagerApproval: https://outlook.office.com/webhook/yyy

**Expected behavior**
No warnings should be issued

**Screenshots**

**Additional context**
Please change the default value for "connectors" from {} to [] (since an array is expected not an object). This should fix the warnings.

**Comment by bzon** [comment]
Thanks for submitting this issue!

This is now fixed in https://github.com/prometheus-msteams/prometheus-msteams/commit/9611b1ed12ef715c123ca9cad370c4016cc0767a and helm chart release 0.4.5
