### ISSUE TITLE
Docker hub account is gone

### ISSUE THREAD

**Issue by timo-reymann** [prometheus-msteams/prometheus-msteams#111]
The account on docker hub can no longer be found and so the image cant be pulled.

Is this intended, and if it is could you please fix the documentation to point to the new account? :)

**Comment by Knappek** [comment]
@timo-reymann we store the images on dockerhub and quay:
* quay.io/prometheusmsteams/prometheus-msteams
* docker.io/prometheusmsteams/prometheus-msteams

Documentation is fixed in #112 .

Please close this issue if the readme fixes are correct.

**Comment by bzon** [comment]
@timo-reymann please use the one hosted in quay.io https://quay.io/repository/prometheusmsteams/prometheus-msteams?tab=tags

If you are trying to pull from the old repository `bzon/prometheus-msteams`, take note that there have been newly released versions since the migration to quay.

**Comment by timo-reymann** [comment]
@bzon Okay thanks for the info, i will use quay.io then ;)
