### ISSUE TITLE
[BUG] v1.3.3 linux SHA256 is wrong

### ISSUE THREAD

**Issue by jdelee** [prometheus-msteams/prometheus-msteams#119]
`curl -fsLo prometheus-msteams-linux-amd64v1.3.3 https://github.com/prometheus-msteams/prometheus-msteams/releases/download/v1.3.3/prometheus-msteams-linux-amd64
`
`shasum -a 256 prometheus-msteams-linux-amd64v1.3.3
fd1ccc4efc113e9f47b293cf7792a913f577bd64e4355156535815bf05054bca  prometheus-msteams-linux-amd64v1.3.3`

`curl -fsLo shasum256.txtv1.3.3 https://github.com/prometheus-msteams/prometheus-msteams/releases/download/v1.3.3/shasum256.txt`

`grep linux shasum256.txtv1.3.3
58c625a71deb379e20109c4624991c57030630547386aaddfa49d31727e0832d  prometheus-msteams-linux-amd64`

these procedures produce the correct sums with v 1.3.2

**Comment by Knappek** [comment]
Thank you @jdelee for reporting this, we fixed it, should be correct now.
