### ISSUE TITLE
problem sending alerts to msteams

### ISSUE THREAD

**Issue by yishaihl** [prometheus-msteams/prometheus-msteams#120]
hey guys,
i'm trying to set it up, but unfortunately i'm not getting the messages to the channel. 

prometheus-operator-8.5.13
eks kubernetes cluster-1.14 
helm v3.1.2

i configured k8s alertmanager config file & prometheus-msteams config.yaml (as described below) and initiate the following command:  

helm upgrade --install prometheus-msteams -f config.yaml prometheus-msteams/prometheus-msteams

**alertmanager.yaml**

https://ibb.co/n1WbVk3

**prometheus-msteams - config.yaml**

https://ibb.co/1QjzqfM

i have experience setting up Slack in prometheus operator and my web-hook is working flawless with another AWS lambda that sends notifications.

any idea what i'm missing here?

Thanks a lot for your help.

**Comment by bzon** [comment]
Hi @yishaihl you are just simply using the wrong endpoint from your alertmanager configuration. See the answer here https://github.com/prometheus-msteams/prometheus-msteams/issues/117#issuecomment-617177502

**Comment by bzon** [comment]
I also updated the sample values file to avoid confusion in the future!

https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/README.md#prepare-the-deployment-configuration

**Comment by yishaihl** [comment]
@bzon thanks a lot man for your quick response working!!
