### ISSUE TITLE
[BUG] 403 Forbidden error

### ISSUE THREAD

**Issue by Streeter220** [prometheus-msteams/prometheus-msteams#121]
Hi, i am experiencing some problems when alertmanager is sending POST to a connector, does anyone know what this could be?

Apr 27 15:16:44 <server_name> alertmanager[34297]: level=error ts=2020-04-27T13:16:44.648Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 403: http://<server_name>:2000/low_priority_channel"

**Comment by Knappek** [comment]
Hi @Streeter220 ,
I think this is not an error in promteams but rather in Alertmanager, the error is being throwed in [this line](https://github.com/prometheus/alertmanager/blob/master/notify/notify.go#L670).
There is a [similar issue](https://github.com/prometheus/alertmanager/issues/1494) (which is closed but apparently not solved). I would love to help you anyways but I haven't seen this error so far. I would suggest to re-open the above mentioned issue at alertmanager.
