### ISSUE TITLE
[BUG]  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by crossbill** [prometheus-msteams/prometheus-msteams#127]
Binary Version : 1.3.4
Running : curl -X POST -d @prom-alert.json http://localhost:2000/alertmanager
Machine behind firewall

Error:
2020/05/22 11:58:29 http: panic serving 127.0.0.1:54426: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
net/http.(*conn).serve.func1(0xc00028edc0)
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/net/http/server.go:1767 +0x139
panic(0xbb8f80, 0x1386a90)
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/prometheus/alertmanager/template.(*Template).ExecuteTextString(0x0, 0xcb2eef, 0x1d, 0xb574c0, 0xc000073f20, 0xc000073e60, 0x133cf34, 0x1, 0xc0000382a0)
	/home/travis/gopath/pkg/mod/github.com/prometheus/alertmanager@v0.20.0/template/template.go:94 +0x3a
github.com/prometheus-msteams/prometheus-msteams/pkg/card.(*templatedCard).executeTemplate(0xc000041d80, 0xc000073e60, 0x133cf34, 0x1, 0xc0000382a0, 0x21, 0x0, 0xe5d420, 0xc0003cad50, 0xc000109000)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/card/templated_card.go:68 +0x158
github.com/prometheus-msteams/prometheus-msteams/pkg/card.(*templatedCard).Convert(0xc000041d80, 0xe5d420, 0xc0003cad20, 0xc000073e60, 0x133cf34, 0x1, 0xc0000382a0, 0x21, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/card/templated_card.go:33 +0x115
github.com/prometheus-msteams/prometheus-msteams/pkg/card.loggingMiddleware.Convert(0xe4b140, 0xc0002e7bc0, 0xe4b3a0, 0xc000041d80, 0xe5d420, 0xc0003cad20, 0xc000073e60, 0x133cf34, 0x1, 0xc0000382a0, ...)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/card/converter.go:92 +0x1a1
github.com/prometheus-msteams/prometheus-msteams/pkg/service.simpleService.Post(0xe4c220, 0xc00000dfa0, 0xc0002e7bf0, 0x7ffed69056ed, 0xc2, 0xe5d420, 0xc0003cad20, 0xc000073e60, 0x133cf34, 0x1, ...)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/service/service.go:45 +0x147
github.com/prometheus-msteams/prometheus-msteams/pkg/service.loggingService.Post(0xe4b140, 0xc0002e7a70, 0xe4c260, 0xc0002e7c50, 0xe5d420, 0xc0003ca9f0, 0xc000073e60, 0x133cf34, 0x1, 0xc0000382a0, ...)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/service/logging.go:33 +0x136
github.com/prometheus-msteams/prometheus-msteams/pkg/transport.addRoute.func1(0xe73fc0, 0xc00028ee60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/transport/transport.go:86 +0x695
github.com/labstack/echo/v4.WrapMiddleware.func1.1.1(0xe5b660, 0xc0003ca990, 0xc0002b1100)
	/home/travis/gopath/pkg/mod/github.com/labstack/echo/v4@v4.1.14/echo.go:779 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc0003ca8d0, 0xe5b660, 0xc0003ca990, 0xc0002b1100)
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/net/http/server.go:2007 +0x44
github.com/prometheus-msteams/prometheus-msteams/pkg/transport.opencensusMiddleware.func1.1(0xe5b660, 0xc0003ca990, 0xc0002b1100)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/transport/transport.go:40 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc0003c8780, 0xe5b660, 0xc0003ca990, 0xc0002b1100)
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc000031220, 0xe5b660, 0xc0003ca990, 0xc0002b0d00)
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.22.2/plugin/ochttp/server.go:92 +0x2b9
github.com/labstack/echo/v4.WrapMiddleware.func1.1(0xe73fc0, 0xc00028ee60, 0x139d900, 0x1)
	/home/travis/gopath/pkg/mod/github.com/labstack/echo/v4@v4.1.14/echo.go:780 +0x137
github.com/prometheus-msteams/prometheus-msteams/pkg/transport.kitLoggerMiddleware.func1.1(0xe73fc0, 0xc00028ee60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/prometheus-msteams/prometheus-msteams/pkg/transport/transport.go:60 +0x109
github.com/labstack/echo/v4.(*Echo).add.func1(0xe73fc0, 0xc00028ee60, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/labstack/echo/v4@v4.1.14/echo.go:509 +0x8a
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000a1e0, 0xe5a5e0, 0xc0003cc2a0, 0xc0002b0d00)
	/home/travis/gopath/pkg/mod/github.com/labstack/echo/v4@v4.1.14/echo.go:620 +0x16c
net/http.serverHandler.ServeHTTP(0xc0003cc1c0, 0xe5a5e0, 0xc0003cc2a0, 0xc0002b0d00)
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00028edc0, 0xe5d360, 0xc0003c44c0)
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.13.7.linux.amd64/src/net/http/server.go:2928 +0x384

**Comment by Knappek** [comment]
@crossbill I can't reproduce this error. Could you please provide the card template that you are using and `prom-alert.json`?

**Comment by marcioa6** [comment]
I was able to reproduce this error by starting it as a service, it works perfectly fine when starting using the regular command.

```
# cat prom-alert.json
{
    "version": "4",
    "groupKey": "{}:{alertname=\"high_memory_load\"}",
    "status": "firing",
    "receiver": "teams_proxy",
    "groupLabels": {
        "alertname": "high_memory_load"
    },
    "commonLabels": {
        "alertname": "high_memory_load",
        "monitor": "master",
        "severity": "warning"
    },
    "commonAnnotations": {
        "summary": "Server High Memory usage"
    },
    "externalURL": "http://docker.for.mac.host.internal:9093",
    "alerts": [
        {
            "labels": {
                "alertname": "high_memory_load",
                "instance": "10.80.40.11:9100",
                "job": "docker_nodes",
                "monitor": "master",
                "severity": "warning"
            },
            "annotations": {
                "description": "10.80.40.11 reported high memory usage with 23.28%.",
                "summary": "Server High Memory usage"
            },
            "startsAt": "2018-03-07T06:33:21.873077559-05:00",
            "endsAt": "0001-01-01T00:00:00Z"
        }
    ]
}
```

**Comment by marcioa6** [comment]
> I was able to reproduce this error by starting it as a service, it works perfectly fine when starting using the regular command.
> 
> ```
> # cat prom-alert.json
> {
>     "version": "4",
>     "groupKey": "{}:{alertname=\"high_memory_load\"}",
>     "status": "firing",
>     "receiver": "teams_proxy",
>     "groupLabels": {
>         "alertname": "high_memory_load"
>     },
>     "commonLabels": {
>         "alertname": "high_memory_load",
>         "monitor": "master",
>         "severity": "warning"
>     },
>     "commonAnnotations": {
>         "summary": "Server High Memory usage"
>     },
>     "externalURL": "http://docker.for.mac.host.internal:9093",
>     "alerts": [
>         {
>             "labels": {
>                 "alertname": "high_memory_load",
>                 "instance": "10.80.40.11:9100",
>                 "job": "docker_nodes",
>                 "monitor": "master",
>                 "severity": "warning"
>             },
>             "annotations": {
>                 "description": "10.80.40.11 reported high memory usage with 23.28%.",
>                 "summary": "Server High Memory usage"
>             },
>             "startsAt": "2018-03-07T06:33:21.873077559-05:00",
>             "endsAt": "0001-01-01T00:00:00Z"
>         }
>     ]
> }
> ```
I troubleshoot it further and was able to make it work using 
-template-file with a full path.
Eg.:
-template-file /foor/bar/default-message-card.tmpl

Please try that @crossbill 

--Marcio Assis

**Comment by crossbill** [comment]
Thanks Marcia, did figure it out, but haven't updated here.
