### ISSUE TITLE
Cluster name in alert message

### ISSUE THREAD

**Issue by andrea-82** [prometheus-msteams/prometheus-msteams#131]
Hi,

I have this implemented this in a couple of cluster.
All the alerts come as "Prometheus Alert (firing)", so I can't tell which cluster this alerts come from.

I could create a different MS Teams webhook per cluster but I was wondering whether there was an easy way to set the cluster name in the alert.

If it needs to be setup in Alertmanager it would be helpful to know what setting does the trick, as I could not find it.

Regards,
Andrea

**Comment by Knappek** [comment]
Hi Andrea, 
you are probably using the [default-message-card.tmpl](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl). The title is defined in [this line](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl#L24). You can easily create your own template following [this guide](https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-to-ms-teams).
Hope this helps.

**Comment by andrea-82** [comment]
That's awesome, thanks @Knappek!

If anyone else is also using this with helm/terraform/terragrunt this is how I included the whole thing (including the custom template):

`resource "helm_release" "prometheus-msteams" {
  name       = "prometheus-msteams"
  repository = "https://prometheus-msteams.github.io/helm-chart/"
  chart      = "prometheus-msteams"
  namespace  = "admin"
  version    = "0.5.1"

  values = [
    yamlencode(
      {
        replicaCount = "2",
        connectors = [
          { main = "https://<MS-TEAMS-webhook>" }
        ],
        customCardTemplate = "${templatefile("ms-teams.card.tmpl", { cluster_name: "k8s-${var.common_vars["environment"]}"})}"
      }
    )
  ]
}`

In the template I can use "${cluster_name}" anywhere to get terraform to replace it with the actual value.

I hope it helps someone else too!
