### ISSUE TITLE
Not pincking the configuration given in the file , localhost:2000/config returns null 

### ISSUE THREAD

**Issue by NarendranathPanda** [prometheus-msteams/prometheus-msteams#132]
**Describe the bug**
Running the promethus-msteams in a standalone centos7 machine as a systemd process

**Version**
1.3.5 version of prometheus-msteams.

**To Reproduce**
regular steps mentioned in the README.md file at home page 

**Expected behavior**
Not showing the configuration properly . 
``` curl localhost:2000/config ```
return 
``` null ```

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/3488520/84274806-ed486e80-ab4d-11ea-9328-ff6c997182f2.png)

**Comment by NarendranathPanda** [comment]
Yes

**Comment by Knappek** [comment]
Hello @NarendranathPanda , your command is not correct. Running `./promteams server` is an old way to do it. Furthermore the input flags `-l` and `-p` are not supported.

How did you start the service? Can you provide the systemd file you are using?

**Comment by naren4b** [comment]
Yes it works , Please feel free to close the issue
