### ISSUE TITLE
Display the version with the '-version' flag

### ISSUE THREAD

**Issue by nkn1111** [prometheus-msteams/prometheus-msteams#136]
**Is your feature request related to a problem? Please describe.**
To download a newer version would like to check the current installed version and download if necessary.

**Describe the solution you'd like**
Get the current installed version using a `-version` flag with the binary.

eg: `./prometheus-msteams-linux-amd64 --version` should give current installed version like the other prometheus exporters.

 **Describe alternatives you've considered**

**Additional context**

**Comment by nkn1111** [comment]
Thanks a lot @Knappek . But the `v1.4.0` bugs me, would be great if the output looks more cleaner like `1.4.0`. Thanks a lot anyway.

**Comment by Knappek** [comment]
I don't know how you use the version, maybe in your CI pipeline, but you can easily cut the 'v', can't you? I don't think we will change this as it's a quite common format with semver.
