### ISSUE TITLE
prometheus-msteams deployment fails on helm upgrade/install

### ISSUE THREAD

**Issue by farooqdevops** [prometheus-msteams/prometheus-msteams#139]
Hi

i am able to install the chart "prometheus-msteams " on my k8 cluster but my deployment fails. I have added pod logs also here. Can someone have a look to see what's wrong with my deployment of chart.

'$ helm upgrade --debug prometheus-msteams ./prometheus-msteams/ --set connectors=<connector-url>'

`$ kubectl get pods -l app=prometheus-msteams --namespace default -w

NAME READY STATUS RESTARTS AGE

prometheus-msteams-5844f69fd6-whzsv 0/1 CrashLoopBackOff 7 11m
`

`$ kubectl logs -f prometheus-msteams-5844f69fd6-whzsv

{"caller":"main.go:148","err":"yaml: unmarshal errors:\n line 2: cannot unmarshal !!str https:/... into []map[string]string","ts":"2020-07-16T13:36:46.120179268Z"}
`

**Comment by Knappek** [comment]
@farooqdevops which version of prometheus-msteams are you using? Could you also share the whole `helm` command please? it seems like you have misconfigured `connectors`.

**Comment by farooqdevops** [comment]
@Knappek thanks for reply.
I am using prometheus-msteam version 0.5.1

i used these commands to deploy my helm chart:
'$ git clone https://github.com/bzon/prometheus-msteams
'$ cd prometheus-msteams/chart'
'$ helm upgrade --debug prometheus-msteams ./prometheus-msteams/ --set connectors=https://outlook.office.com/webhook/xyz'

**Comment by Knappek** [comment]
1. The latest version of prometheus-msteams is v1.4.0, it is highly recommended to upgrade.
2. connectors is a list that contains a key-value pair, and not a string like you configured it. Please refer to the [Helm Chart README](https://github.com/prometheus-msteams/prometheus-msteams/tree/master/chart/prometheus-msteams) for further details. 

Let me know if this helps.

**Comment by farooqdevops** [comment]
@Knappek thanks for your help. It works now.

**Comment by zannxD** [comment]
@Knappek my helm upgrade command is as follows:
helm upgrade --install prometheus-msteams -n monitoring --set connectors.alertmanager=https://outlook.office.com/webhook/xxx/xxx --set-file customCardTemplate=/home/prometheus-msteams/chart/prometheus-msteams/card.tmpl prometheus-msteams/prometheus-msteams

and the pod is crashlooping with the same error: 
{"caller":"main.go:148","err":"yaml: unmarshal errors:\n  line 2: cannot unmarshal !!map into []map[string]string","ts":"2021-01-11T05:19:34.985140513Z"}

**Comment by Knappek** [comment]
Hi @zannxD I am sorry for the late response. Which version of the chart are you using? It seems to be quite old as `connectors.alertmanager` is not possible because `connectors` is an array. Could you try updating to the latest chart version `1.0.2` and try again?
