### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by hailong1004** [prometheus-msteams/prometheus-msteams#140]
**Is your feature request related to a problem? Please describe.**
only 10 maximum alerts in one message when a alert group more then 10 alert

**Describe the solution you'd like**
could able set maximum alerts in one message

**Describe alternatives you've considered**
When I set up group_by in alertmanager.yml, I have an alert manager with 25 alerts, but it will be split into 3 messages each with a maximum of 10 alerts. I actually want to send these 25 alarms in one message instead of being split into 10 alarms for each message.

my alertmanager.yml :
route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'msteams'  
  routes:
    - receiver: msteams
      match_re:
        severity: .*

**Additional context**

**Comment by Knappek** [comment]
Unfortunately we have to split this into multiple messages as it is a [MS Teams limitation](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#notes-on-the-office-365-connector-card):

> Each Connector card can display a maximum of 10 sections, and each section can contain a maximum of 5 images and 5 actions.
