### ISSUE TITLE
Reload configuration upon receiving a signal

### ISSUE THREAD

**Issue by lmasaya** [prometheus-msteams/prometheus-msteams#145]
I'm running **promteams** as a long lived process and would like to be able to update the configuration of the channels that get notified without restarting the proxy.

I would like to have the application catch a given signal, say SIGHUP or SIGUSR1, to reload its configuration file.

An alternate solution would be to provide a URL path to reload the application configuration, say /reload

I see that you are already handling SIGINT and SIGTERM, so I suspect that this path would be easier.
https://github.com/prometheus-msteams/prometheus-msteams/blob/aa6768a4c5c1c9f5017f6d1d7d267af2e1080fcf/cmd/server/main.go#L318

**Comment by Knappek** [comment]
Hi @lmasaya thank you for this feature request. 

Can you provide a little bit of background why you want/need this feature? 

I am asking because if you, for example, are running promteams on Kubernetes as a container, best practice is to treat containers as immutable objects and do a rolling update deployment. With rolling updates you will further have no downtime of the promteams endpoint.

**Comment by lmasaya** [comment]
> Hi @lmasaya thank you for this feature request.
> 
> Can you provide a little bit of background why you want/need this feature?
> 
> I am asking because if you, for example, are running promteams on Kubernetes as a container, best practice is to treat containers as immutable objects and do a rolling update deployment. With rolling updates you will further have no downtime of the promteams endpoint.

I'm currently running this in a Nomad Cluster and the configuration file gets templated from a secret in a Vault KV store. I treat webhooks as a secret, because just having them would allow me to spam a channel. I have the job set to restart the application when that template gets changed, due to changes in the secret, but it doesn't seem to work properly or at least consistently. So I get what you mean with having immutable objects. I'm looking at changing this to sending a signal to the app to reload its configuration as a way to solve this.

I've looked at the runGroup package and realize that my suggestion to use a SIGHUP/SIGUSR1 signal makes no sense for reloading config, as it will cause the process to terminate. I'll test to see if sending SIGTERM is enough to get the process to terminate and get redeployed properly.

**Comment by lmasaya** [comment]
> > Hi @lmasaya thank you for this feature request.
> > Can you provide a little bit of background why you want/need this feature?
> > I am asking because if you, for example, are running promteams on Kubernetes as a container, best practice is to treat containers as immutable objects and do a rolling update deployment. With rolling updates you will further have no downtime of the promteams endpoint.
> 
> I'm currently running this in a Nomad Cluster and the configuration file gets templated from a secret in a Vault KV store. I treat webhooks as a secret, because just having them would allow me to spam a channel. I have the job set to restart the application when that template gets changed, due to changes in the secret, but it doesn't seem to work properly or at least consistently. So I get what you mean with having immutable objects. I'm looking at changing this to sending a signal to the app to reload its configuration as a way to solve this.
> 
> I've looked at the runGroup package and realize that my suggestion to use a SIGHUP/SIGUSR1 signal makes no sense for reloading config, as it will cause the process to terminate. I'll test to see if sending SIGTERM is enough to get the process to terminate and get redeployed properly.
> 
> I still consider that this might be a good feature for non-containerized use cases.

It seems it's an issue of a large TTL of Vault secrets that causes Nomad not to notice the change. So, this feature won't help with my issue. Feel free to close if you think it isn't helpful to the larger community.

**Comment by Knappek** [comment]
@lmasaya I will close this issue as I think it won't be a huge benefit to the majority of the prometheus-msteams users. I understand that config-reload is beneficial for critical services that have to be up and running all the time, which is not the case for prometheus-msteams in my opinion.

Thanks for the request anyway. I am happy to re-open if someone disagrees.
