### ISSUE TITLE
[BUG] sending a message behind a corporate proxy

### ISSUE THREAD

**Issue by jribmartins** [prometheus-msteams/prometheus-msteams#147]
**Describe the bug**
`{"caller":"transport.go:88","err":"http client failed: Post <webhookurl>:  dial tcp: lookup outlook.office.com on ...: no such host","ts":"2020-08-11T07:32:32.074670644Z"}`

**Version**
v.1.4.1

**To Reproduce**
just try to send a message behind a corporate proxy like `http_config`

**Expected behavior**
a way to add the proxy url

**Comment by michalrudko** [comment]
So it there a way to add a corporate proxy settings? Where is the proper place to define it?

**Comment by Knappek** [comment]
@michalrudko you just need to set the proxy environment variables `HTTP_PROXY` AND `HTTPS_PROXY`.
