### ISSUE TITLE
[BUG] Helm-Chart not published

### ISSUE THREAD

**Issue by ckotzbauer** [prometheus-msteams/prometheus-msteams#149]
**Describe the bug**
Could you please publish the new versions of the helm-chart? The "helm-chart" repository was not updated for the latest versions.
Thanks!

**Comment by Knappek** [comment]
Hi @ckotzbauer, I don't understand. According to the [Chart.yaml](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/Chart.yaml) the version should be [0.5.1](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/Chart.yaml#L5) which is also the latest release of the [helm chart](https://github.com/prometheus-msteams/helm-chart). Am I wrong?

**Comment by ckotzbauer** [comment]
The charts directory in this repo is only where the chart is developed. But this is not the location where the chart is published. This is https://github.com/prometheus-msteams/helm-chart. And there is still 0.4.0

**Comment by Knappek** [comment]
Sorry, but are you on the wrong branch? I see `0.5.1`being published:

![image](https://user-images.githubusercontent.com/18685317/91982987-54c82180-ed2b-11ea-8a12-f1f84ec6ef56.png)

**Comment by ckotzbauer** [comment]
Sorry, I wasn't clear enough. Yes, 0.5.1 is published and it is the latest chart-version. But this version doesn't point to the newest version of the app. The chart uses 1.3.5 and the newest is 1.4.1

**Comment by Knappek** [comment]
okay, this is fine though, you can easily change it with `image.tag` variable. The reason for this pointing to `1.3.5` is that chart version `0.5.1` started with app version `1.3.5`. Although we didn't change chart version in subsequent releases, hence we haven't changed the app version either, as it would mean a new chart release (or replacing the 0.5.1 release which I wouldn't recommend due to violence of immutability). Does that make sense?

**Comment by ckotzbauer** [comment]
Yes, of course I can change the version manually. But it would be better (and that's common practice) that the appVersion is updated anytime a new version is released. This makes also a new version of the chart itself neccessary, cause (as you said) the chart-version is immutable.

**Comment by Knappek** [comment]
As I think now, probably you are right :D. Actually I was talking with @bzon to make the process of publishing a new helm chart release based on changes in the root repo more automated anyway. Let's use this issue to tackle this. 

I would appreciate your contribution if you like as my time is limited currently :)

**Comment by ckotzbauer** [comment]
Great :)
Of course, I can help here. I personally prefer a setup with github-actions where the chart is hosted with gh-pages in the same repo. I use this for my own chart-repo https://github.com/ckotzbauer/helm-charts

If this is sth. which would be an option, a can make a PR.

**Comment by Knappek** [comment]
hah, I didn't know you can use gh-pages for that. That is awesome. Yes absolutely, this is nice, we also thought about moving to github actions. @bzon what do you think?

**Comment by bzon** [comment]
This will make our helm publishing much easier. @ckotzbauer 👍

**Comment by ckotzbauer** [comment]
Great, I think I will have time on the weekend to make a PR. :+1:
