### ISSUE TITLE
[BUG] Some alerts are getting an error :"Summary or Text is required.","response_status":400

### ISSUE THREAD

**Issue by Gizmos777** [prometheus-msteams/prometheus-msteams#153]
**Describe the bug**
Some alerts aren't reaching MS team. I see in pod logs a message with an error  

> {"caller":"logging.go:25","err":null,"level":"debug","response_message":"Summary or Text is required.","response_status":400,"ts":"2020-09-24T06:51:38.861533204Z","webhook_url":"https://outlook.office.com/webhook/sjiofjiosdjfjs/IncomingWebhook/1222222222222142414/asjfousour0982irowp-392-"}

**Version**
The docker image or release version of prometheus-msteams.

v1.4.1
**To Reproduce**

I'll get same error if I send a request to a prometheus-msteams directly without:

> 
>     "commonLabels": {
>         "alertname": "high memory load",
>     },

Log of the error

> {
>    "alert":{
>       "receiver":"prometheus-msteams",
>       "status":"firing",
>       "alerts":[
>          {
>             "status":"resolved",
>             "labels":{
>                "alertname":"PrometheusOperatorListErrors",
>                "controller":"alertmanager",
>                "namespace":"monitoring",
>                "prometheus":"monitoring/monitor-prometheus-operato-prometheus",
>                "severity":"warning"
>             },
>             "annotations":{
>                "message":"Errors while performing List operations in controller alertmanager in monitoring namespace."
>             },
>             "startsAt":"2020-09-24T06:50:08.29Z",
>             "endsAt":"2020-09-24T07:35:08.29Z",
>             "generatorURL":"http://monitor-prometheus-operato-prometheus.monitoring:9090/graph?g0.expr=%28sum+by%28controller%2C+namespace%29+%28rate%28prometheus_operator_list_operations_failed_total%7Bjob%3D%22monitor-prometheus-operato-operator%22%2Cnamespace%3D%22monitoring%22%7D%5B1h%5D%29%29+%2F+sum+by%28controller%2C+namespace%29+%28rate%28prometheus_operator_list_operations_total%7Bjob%3D%22monitor-prometheus-operato-operator%22%2Cnamespace%3D%22monitoring%22%7D%5B1h%5D%29%29%29+%3E+0.4&g0.tab=1",
>             "fingerprint":"e1cc0cd0c3f3b246"
>          },
>          {
>             "status":"resolved",
>             "labels":{
>                "alertname":"PrometheusOperatorListErrors",
>                "controller":"prometheus",
>                "namespace":"monitoring",
>                "prometheus":"monitoring/monitor-prometheus-operato-prometheus",
>                "severity":"warning"
>             },
>             "annotations":{
>                "message":"Errors while performing List operations in controller prometheus in monitoring namespace."
>             },
>             "startsAt":"2020-09-24T06:50:08.29Z",
>             "endsAt":"2020-09-24T07:35:08.29Z",
>             "generatorURL":"http://monitor-prometheus-operato-prometheus.monitoring:9090/graph?g0.expr=%28sum+by%28controller%2C+namespace%29+%28rate%28prometheus_operator_list_operations_failed_total%7Bjob%3D%22monitor-prometheus-operato-operator%22%2Cnamespace%3D%22monitoring%22%7D%5B1h%5D%29%29+%2F+sum+by%28controller%2C+namespace%29+%28rate%28prometheus_operator_list_operations_total%7Bjob%3D%22monitor-prometheus-operato-operator%22%2Cnamespace%3D%22monitoring%22%7D%5B1h%5D%29%29%29+%3E+0.4&g0.tab=1",
>             "fingerprint":"9dc9964403169441"
>          },
>          {
>             "status":"resolved",
>             "labels":{
>                "alertname":"PrometheusOperatorListErrors",
>                "controller":"thanos",
>                "namespace":"monitoring",
>                "prometheus":"monitoring/monitor-prometheus-operato-prometheus",
>                "severity":"warning"
>             },
>             "annotations":{
>                "message":"Errors while performing List operations in controller thanos in monitoring namespace."
>             },
>             "startsAt":"2020-09-24T06:50:08.29Z",
>             "endsAt":"2020-09-24T07:34:38.29Z",
>             "generatorURL":"http://monitor-prometheus-operato-prometheus.monitoring:9090/graph?g0.expr=%28sum+by%28controller%2C+namespace%29+%28rate%28prometheus_operator_list_operations_failed_total%7Bjob%3D%22monitor-prometheus-operato-operator%22%2Cnamespace%3D%22monitoring%22%7D%5B1h%5D%29%29+%2F+sum+by%28controller%2C+namespace%29+%28rate%28prometheus_operator_list_operations_total%7Bjob%3D%22monitor-prometheus-operato-operator%22%2Cnamespace%3D%22monitoring%22%7D%5B1h%5D%29%29%29+%3E+0.4&g0.tab=1",
>             "fingerprint":"da74e2813003b932"
>          },
>          {
>             "status":"firing",
>             "labels":{
>                "alertname":"CPUThrottlingHigh",
>                "container":"promitor-agent-scraper",
>                "namespace":"monitoring",
>                "pod":"promitor-agent-scraper-7b5cddbccd-sz4wp",
>                "prometheus":"monitoring/monitor-prometheus-operato-prometheus",
>                "severity":"info"
>             },
>             "annotations":{
>                "message":"67.12% throttling of CPU in namespace monitoring for container promitor-agent-scraper in pod promitor-agent-scraper-7b5cddbccd-sz4wp.",
>                "runbook_url":"https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh"
>             },
>             "startsAt":"2020-09-23T18:37:47.016Z",
>             "endsAt":"0001-01-01T00:00:00Z",
>             "generatorURL":"http://monitor-prometheus-operato-prometheus.monitoring:9090/graph?g0.expr=sum+by%28container%2C+pod%2C+namespace%29+%28increase%28container_cpu_cfs_throttled_periods_total%7Bcontainer%21%3D%22%22%7D%5B5m%5D%29%29+%2F+sum+by%28container%2C+pod%2C+namespace%29+%28increase%28container_cpu_cfs_periods_total%5B5m%5D%29%29+%3E+%2825+%2F+100%29&g0.tab=1",
>             "fingerprint":"b62366adba3f1b8a"
>          }
>       ],
>       "groupLabels":{
>          
>       },
>       "commonLabels":{
>          "namespace":"monitoring",
>          "prometheus":"monitoring/monitor-prometheus-operato-prometheus"
>       },
>       "commonAnnotations":{
>          
>       },
>       "externalURL":"http://monitor-prometheus-operato-alertmanager.monitoring:9093",
>       "version":"4",
>       "groupKey":"{}:{}"
>    },
>    "caller":"converter.go:86",
>    "card":{
>       "@context":"http://schema.org/extensions",
>       "@type":"MessageCard",
>       "title":"Prometheus Alert (firing)",
>       "text":"",
>       "summary":"",
>       "themeColor":"808080",
>       "sections":[
>          {
>             "activityTitle":"[](http://monitor-prometheus-operato-alertmanager.monitoring:9093)",
>             "markdown":true,
>             "facts":[
>                {
>                   "name":"message",
>                   "value":"Errors while performing List operations in controller alertmanager in monitoring namespace."
>                },
>                {
>                   "name":"alertname",
>                   "value":"PrometheusOperatorListErrors"
>                },
>                {
>                   "name":"controller",
>                   "value":"alertmanager"
>                },
>                {
>                   "name":"namespace",
>                   "value":"monitoring"
>                },
>                {
>                   "name":"prometheus",
>                   "value":"monitoring/monitor-prometheus-operato-prometheus"
>                },
>                {
>                   "name":"severity",
>                   "value":"warning"
>                }
>             ]
>          },
>          {
>             "activityTitle":"[](http://monitor-prometheus-operato-alertmanager.monitoring:9093)",
>             "markdown":true,
>             "facts":[
>                {
>                   "name":"message",
>                   "value":"Errors while performing List operations in controller prometheus in monitoring namespace."
>                },
>                {
>                   "name":"alertname",
>                   "value":"PrometheusOperatorListErrors"
>                },
>                {
>                   "name":"controller",
>                   "value":"prometheus"
>                },
>                {
>                   "name":"namespace",
>                   "value":"monitoring"
>                },
>                {
>                   "name":"prometheus",
>                   "value":"monitoring/monitor-prometheus-operato-prometheus"
>                },
>                {
>                   "name":"severity",
>                   "value":"warning"
>                }
>             ]
>          },
>          {
>             "activityTitle":"[](http://monitor-prometheus-operato-alertmanager.monitoring:9093)",
>             "markdown":true,
>             "facts":[
>                {
>                   "name":"message",
>                   "value":"Errors while performing List operations in controller thanos in monitoring namespace."
>                },
>                {
>                   "name":"alertname",
>                   "value":"PrometheusOperatorListErrors"
>                },
>                {
>                   "name":"controller",
>                   "value":"thanos"
>                },
>                {
>                   "name":"namespace",
>                   "value":"monitoring"
>                },
>                {
>                   "name":"prometheus",
>                   "value":"monitoring/monitor-prometheus-operato-prometheus"
>                },
>                {
>                   "name":"severity",
>                   "value":"warning"
>                }
>             ]
>          },
>          {
>             "activityTitle":"[](http://monitor-prometheus-operato-alertmanager.monitoring:9093)",
>             "markdown":true,
>             "facts":[
>                {
>                   "name":"message",
>                   "value":"67.12% throttling of CPU in namespace monitoring for container promitor-agent-scraper in pod promitor-agent-scraper-7b5cddbccd-sz4wp."
>                },
>                {
>                   "name":"runbook_url",
>                   "value":"https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh"
>                },
>                {
>                   "name":"alertname",
>                   "value":"CPUThrottlingHigh"
>                },
>                {
>                   "name":"container",
>                   "value":"promitor-agent-scraper"
>                },
>                {
>                   "name":"namespace",
>                   "value":"monitoring"
>                },
>                {
>                   "name":"pod",
>                   "value":"promitor-agent-scraper-7b5cddbccd-sz4wp"
>                },
>                {
>                   "name":"prometheus",
>                   "value":"monitoring/monitor-prometheus-operato-prometheus"
>                },
>                {
>                   "name":"severity",
>                   "value":"info"
>                }
>             ]
>          }
>       ]
>    },
>    "escaped_underscores":true,
>    "template_file":"/etc/template/card.tmpl",
>    "took":"888.496µs",
>    "ts":"2020-09-24T07:36:36.665643338Z"
> }

**Comment by Knappek** [comment]
@Gizmos777 this is not a bug in prometheus-msteams but rather a requirement of MS teams that either `summary` or `text` is required. None of them is provided in your alert. 
Check out the current default card template, there is a guard implemented if the prometheus alert does not provide any of the fields used for either `summary` or `text`: [this line](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl#L14) fills `summary` with `Prometheus Alert` if neither of `commonAnnotations.summary`, `commonAnnotations.message` nor `commonLabels.alertname` are present in the prometheus alert.

Hope this makes sense, feel free to re-open if you disagree.

**Comment by Gizmos777** [comment]
> Check out the current default card template, there is a guard implemented if the prometheus alert does not provide any of the fields used for either `summary` or `text`: [this line](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl#L14) fills `summary` with `Prometheus Alert` if neither of `commonAnnotations.summary`, `commonAnnotations.message` nor `commonLabels.alertname` are present in the prometheus alert
My card.tmpl file is:

> {{ define "teams.card" }}
> {
>   "@type": "MessageCard",
>   "@context": "http://schema.org/extensions",
>   "themeColor": "{{- if eq .Status "resolved" -}}2DC72D
>                  {{- else if eq .Status "firing" -}}
>                     {{- if eq .CommonLabels.severity "critical" -}}8C1A1A
>                     {{- else if eq .CommonLabels.severity "warning" -}}FFA500
>                     {{- else -}}808080{{- end -}}
>                  {{- else -}}808080{{- end -}}",
>   "summary": "{{- if eq .CommonAnnotations.summary "" -}}
>                   {{- if eq .CommonAnnotations.message "" -}}
>                     {{- .CommonLabels.alertname -}}
>                   {{- else -}}
>                     {{- .CommonAnnotations.message -}}
>                   {{- end -}}
>               {{- else -}}
>                   {{- .CommonAnnotations.summary -}}
>               {{- end -}}",
>   "title": "Prometheus Alert ({{ .Status }})",
>   "sections": [ {{$externalUrl := .ExternalURL}}
>   {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
>     {
>       "activityTitle": "[{{ $alert.Annotations.description }}]({{ $externalUrl }})",
>       "facts": [
>         {{- range $key, $value := $alert.Annotations }}
>         {
>           "name": "{{ $key }}",
>           "value": "{{ $value }}"
>         },
>         {{- end -}}
>         {{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}},{{ end }}
>         {
>           "name": "{{ $key }}",
>           "value": "{{ $value }}"
>         }
>         {{- end }}
>       ],
>       "markdown": true
>     }
>     {{- end }}
>   ]
> }
> {{ end }}

**Comment by Knappek** [comment]
Yeah, you are using an old version of the default template. Please check the differences that I've mentioned. Then you will see why your `summary` value is empty.

**Comment by Gizmos777** [comment]
> Yeah, you are using an old version of the default template. Please check the differences that I've mentioned. Then you will see why your `summary` value is empty.

I checked an alert message:

>       "groupLabels":{
>          
>       },
>       "commonLabels":{
>          "namespace":"monitoring",
>          "prometheus":"monitoring/monitor-prometheus-operato-prometheus"
>       },
>       "commonAnnotations":{
>          
>       },

**Comment by Knappek** [comment]
Yes, and your template requires one of the following for the `summary`:
- `commonAnnotations.summary`
- `commonAnnotations.message`
- `commonLabels.alertname`

and none of them is present in your alert. If you would replace your template's summary section with the [following from the default template](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl#L11-L23) it won't fail as this part has a hard-coded `Prometheus Alert` if nothing is present.

**Comment by Gizmos777** [comment]
> 
> 
> Yes, and your template requires one of the following for the `summary`:
> 
>     * `commonAnnotations.summary`
> 
>     * `commonAnnotations.message`
> 
>     * `commonLabels.alertname`
> 
> 
> and none of them is present in your alert. If you would replace your template's summary section with the [following from the default template](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/default-message-card.tmpl#L11-L23) it won't fail as this part has a hard-coded `Prometheus Alert` if nothing is present.

I got it.
I have a test kubernetes cluster and  i don't have a such problem:

>       "groupLabels":{
>          
>       },
>       "commonLabels":{
>          "alertname":"CPUThrottlingHigh",
>          "prometheus":"monitoring/monitor-prometheus-operato-prometheus",
>          "severity":"info"
>       },
>       "commonAnnotations":{
>          "runbook_url":"https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh"
>       },

**Comment by Gizmos777** [comment]
> 
> 
> Yeah, you are using an old version of the default template. Please check the differences that I've mentioned. Then you will see why your `summary` value is empty.

Where can I get a new version of the default template?

**Comment by Knappek** [comment]
check out the releases page, you can find it in the latest release's assets: https://github.com/prometheus-msteams/prometheus-msteams/releases/tag/v1.4.1

**Comment by Gizmos777** [comment]
> 
> 
> check out the releases page, you can find it in the latest release's assets: https://github.com/prometheus-msteams/prometheus-msteams/releases/tag/v1.4.1

Thank you!
It is working with this default template.
