### ISSUE TITLE
Question: Grafana-like alert card possible with template only?

### ISSUE THREAD

**Issue by trallnag** [prometheus-msteams/prometheus-msteams#158]
I have a question regarding the Go templates, since they are completely new to me. Is it possible to create a template that generates a card similar to the one Grafana emits without changing any Go code?

The specific characteristic I'm interested in is using the label value as a key fact and the numerical value as the fact value.

![Untitled](https://user-images.githubusercontent.com/24834206/95304366-c80e0780-0884-11eb-9be7-4dba12f611c1.png)

I assume that it is possible

**Comment by Knappek** [comment]
hi @trallnag, can you please share the corresponding prometheus alert json? That would help me to help you :)

**Comment by trallnag** [comment]
Grafana has it's own alert engine and so there is no alert in the Prometheus format at all. But [here](https://github.com/grafana/grafana/blob/41d432b5ae68c0fc2261e607289206b79410fcfa/pkg/services/alerting/notifiers/teams.go) is the actual Golang file with the function `Notify` that sends the notification to Teams.

Just wondering how much "logic" I can express with Go templates since Grafana does not use a template but Go code itself

**Comment by Knappek** [comment]
Okay thanks, I will have a look later that day.

**Comment by trallnag** [comment]
@Knappek btw I answered the question myself and will post the result here once I get to it and then close the issue. The templating is not as magic as it first seems :smile: 

Btw I think it would be a good addition to have a place to collect different templates, so maybe in this repository?

**Comment by Knappek** [comment]
haha great 👍 . We do have an [example directory](https://github.com/prometheus-msteams/prometheus-msteams/tree/master/examples) which is also linked in the README. Please put your grafana-like template to that diretory and in the same PR you can update the screenshot in the Readme ;).

**Comment by trallnag** [comment]
PR can be found here https://github.com/prometheus-msteams/prometheus-msteams/pull/159
