### ISSUE TITLE
imagepullSecrets not available with the helmchart.

### ISSUE THREAD

**Issue by pkd809** [prometheus-msteams/prometheus-msteams#160]
Image Pull Secrets is not available with the helmchart request prometheus-msteams helmrelease team to please add the imagepullSecret attribute to the chart.

**Comment by Knappek** [comment]
Now available in chart version `0.7.0`. See [chart readme](https://github.com/prometheus-msteams/prometheus-msteams/tree/master/chart/prometheus-msteams) for more information.
