### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by nfldsantos** [prometheus-msteams/prometheus-msteams#162]
**x509: certificate signed by unknown authority**
Validation error of certificate from outlook.microsoft
Is there any option as we have in AlertManager when sending email, to set the TLS comunication, for example: 
tls_config:
  insecure_skip_verify: true

Meanwhile i am checking how to add the certificate to CA, trying to mount the certificate on the running POD, could that option be also added to helm chart as optional?

**Version**
Helm chart version 0.6.0

**To Reproduce**
1 - Create a webhook in MS teams
2 - Added in the values.yaml the parameters:
**connectors:
- teams_ops_channel: (MS teams webhook url)** 
3 - Send alert to prometheus-msteams

**Expected behavior**
A clear and concise description of what you expected to happen. Provide logs, metrics or traces if possible.

**Screenshots**
{"caller":"transport.go:88","err":"http client failed: Post https://outlook.office.com/webhook/XXXX/IncomingWebhook/XXXXX: x509: certificate signed by unknown authority","ts":"2020-11-04T15:57:29.701993281Z"}
{"caller":"transport.go:52","host":"prometheus-msteams:2000","method":"POST","status":500,"took":"4.785184367s","ts":"2020-11-04T15:57:29.702030396Z","uri":"/teams_ops_channel"}

**Additional context**
When checking the certificate:
![image](https://user-images.githubusercontent.com/46348496/98138151-b5561500-1eba-11eb-933b-624616e510d1.png)

**Comment by Knappek** [comment]
@nfldsantos thank you for filing this issue. 

Indeed we can provide a `-insecure-skip-verify` flag to make it optional to validate the server certificate. I have opened a PR, can you please check out the corresponding branch, build it from source (with `make linux` or `make darwin` or `make windows`), set this flag to `true` and verify that it works pls?

**Comment by laith-leo** [comment]
I'm pretty much getting the same error, prometheus-msteams version is 1.5.1:

`{"caller":"transport.go:133","err":"http client failed: Post \"https://mycompany.webhook.office.com/webhookb2/XXXXXXX\": POST https://mycompany.webhook.office.com/webhookb2/XXXXXXX giving up after 1 attempt(s): Post \"https://mycompany.webhook.office.com/webhookb2/XXXXXX\": x509: certificate signed by unknown authority","ts":"2022-08-21T03:08:16.825758291Z"}
{"caller":"transport.go:66","host":"prometheus-msteams.mon.svc.cluster.local:2000","method":"POST","status":500,"took":"1.087262237s","ts":"2022-08-21T03:08:16.90243817Z","uri":"/alertmanager-mywork"}`

**Comment by laith-leo** [comment]
I'm pretty much getting the same error, prometheus-msteams version is 1.5.1:

`{"caller":"transport.go:133","err":"http client failed: Post \"https://mycompany.webhook.office.com/webhookb2/XXXXXXX\": POST https://mycompany.webhook.office.com/webhookb2/XXXXXXX giving up after 1 attempt(s): Post \"https://mycompany.webhook.office.com/webhookb2/XXXXXX\": x509: certificate signed by unknown authority","ts":"2022-08-21T03:08:16.825758291Z"}
{"caller":"transport.go:66","host":"prometheus-msteams.mon.svc.cluster.local:2000","method":"POST","status":500,"took":"1.087262237s","ts":"2022-08-21T03:08:16.90243817Z","uri":"/alertmanager-mywork"}`

**Comment by kbudde** [comment]
@laith-leo please file a new issue.
We will have to check it

**Comment by laith-leo** [comment]
@kbudde Posted, #259
Thanks!
