### ISSUE TITLE
[BUG] Helm Chart connectors_with_custom_templates not working

### ISSUE THREAD

**Issue by benjamin37** [prometheus-msteams/prometheus-msteams#164]
**Describe the bug**
Trying to add multiple (or even a single) custom msteams card templates with `connectors_with_custom_templates` via the helm chart provided in this repository. According to the [docs](https://github.com/prometheus-msteams/prometheus-msteams/tree/acb9a8092bdb8e40128ca90b2852fe6629396d7d#customise-messages-per-ms-teams-channel) a valid configuration should be:

```
connectors_with_custom_templates:
- request_path: /alert2
  template_file: ./default-message-card.tmpl
  webhook_url: <webhook> 
  escape_underscores: true
```

Now there is no way to get a file with the name `default-message-card.tmpl` inside the pod via the [helm chart](https://github.com/prometheus-msteams/prometheus-msteams/tree/master/chart/prometheus-msteams) right?

**Version**
Version of the helm chart: 0.7.0
Version of prometheus-msteams: 1.4.1

**Comment by Knappek** [comment]
Hi @benjamin37 thank you for using prometheus-msteams and filing your issue. I am trying to understand what issues you are facing.

>Now there is no way to get a file with the name default-message-card.tmpl inside the pod via the helm chart right?

Can you please elaborate, I don't understand this question.

There is [more documentation in the helm chart readme on that topic](https://github.com/prometheus-msteams/prometheus-msteams/tree/master/chart/prometheus-msteams#customise-messages-to-ms-teams). Maybe this helps.

**Comment by benjamin37** [comment]
Hi @Knappek,

in the `connectors_with_custom_templates` I mentioned in my first comment there is a `template_file`. When deploying the helm chart with this configuration, `prometheus-msteams` expects to find a file named `default-message-card.tmpl` in the container. I don't see a way to provide the container with this file.

**Comment by Knappek** [comment]
I see your point. Right now, it is not possible to provide multiple card templates mapping to different request paths. This is definitely something that can be improved. Would you like to contribute and implement this feature in the helm chart?

That being said, it is possible to define a custom card with the following `values.yaml`:

```
replicaCount: 1
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.4.1

container:
  additionalArgs:
    - -debug

connectors:
  - my-alert: https://outlook.office.com/webhook/xxxxx/yyyyy/zzzzz

customCardTemplate: |
  {{ define "teams.card" }}
  {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "{{- if eq .Status "resolved" -}}2DC72D
                  {{- else if eq .Status "firing" -}}
                      {{- if eq .CommonLabels.severity "critical" -}}8C1A1A
                      {{- else if eq .CommonLabels.severity "warning" -}}FFA500
                      {{- else -}}808080{{- end -}}
                  {{- else -}}808080{{- end -}}",
    "summary": "Undesirable behaviour {{ .CommonAnnotations.summary }}",
    "title": "Prometheus Alert ({{ .Status }})",
    "sections": [ {{$externalUrl := .ExternalURL}}
    {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
      {
        "activityTitle": "[{{ $alert.Annotations.description }}]({{ $externalUrl }})", 
        "facts": [
          {{- range $key, $value := $alert.Annotations }}
          {
            "name": "{{ reReplaceAll "_" "\\\\_" $key }}",
            "value": "{{ reReplaceAll "_" "\\\\_" $value }}"
          },
          {{- end -}}
          {{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}},{{ end }}
          {
            "name": "{{ reReplaceAll "_" "\\\\_" $key }}",
            "value": "{{ reReplaceAll "_" "\\\\_" $value }}"
          }
          {{- end }}
        ],
        "markdown": true
      }
      {{- end }}
    ]
    {{- if eq .Status "firing" -}}
    ,
    "potentialAction": [
    {{- if .Alerts -}}
      {
          "@context": "http://schema.org",
          "@type": "ViewAction",
          "name": "Silence Alert",
          {{- range $index, $alert := .Alerts }}
            {{- if eq $index 0}}
              "target": [
                  "{{ $externalUrl }}/#/silences/new?filter=%7B{{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}}%22%2C%20{{ end }}{{ $key }}%3D%22{{ $value }}{{- end }}%22%7D"
              ]
            {{- end }}
          {{- end }}
      }
    {{- end -}}
    ]
    {{- end }}
  }
  {{ end }}
```

When send an alert to the request path `/my-alert` it will using the provided custom template. 

In the end, there is no real benefit in using `connectors_with_custom_templates` in the helm chart yet.

**Comment by benjamin37** [comment]
Sure, with the `customCardTemplate` value of the helm chart it is possible to provide 1 custom ms teams card. But I was talking about `connectors_with_custom_templates` which can not be used for even 1 custom ms teams card in the helm chart if I understand it correctly.
From my understanding `connectors_with_custom_templates` does not work in the helm chart yet.
I'll have a look if I can contribute a fix for the helm chart.

**Comment by Knappek** [comment]
> From my understanding connectors_with_custom_templates does not work in the helm chart yet.

Kind of. What works is the following:

```
connectors_with_custom_templates:
- request_path: /alert2
  template_file: /etc/template/card.tmpl
  webhook_url: <webhook> 
  escape_underscores: true # get the effect of -auto-escape-underscores.
```

It kinda works, but it's not the actual use case of using `connectors_with_custom_templates` which is rather being able to configure different request paths with different templates.

**Comment by benjamin37** [comment]
True, that's the default ms teams cards template that comes with the helm chart.

**Comment by Knappek** [comment]
No I mean together with `customCardTemplate` you can provide your custom template AND use `connectors_with_custom_templates`. But TBH, `connectors_with_custom_templates` does not give you more value to it as all of the parameters can be configured with other helm values as well ;). 

As said, being able to provide multiple templates that are being used for multiple different request paths would be really cool.
