### ISSUE TITLE
Retry sending alert on 503 

### ISSUE THREAD

**Issue by nhe23** [prometheus-msteams/prometheus-msteams#170]
Sometimes api calls on office 365 return 503. This can happen without any clear reason and sometimes it happens due to high loads. That exact case occured today and the alert did not reach MS Teams. However the resolving alert could be sent a few minutes later. 
The log shows that an 503 error occured: 
![image](https://user-images.githubusercontent.com/19340684/101394428-cbdff980-38c8-11eb-972b-ba2cf0342287.png)

It would be nice if the msteams proxy retried sending the alert at least once or twice after a few seconds. This way it can be ensured that a small hiccup of office 365 does not lead to an potentially very important alert not being sent.

**Comment by Knappek** [comment]
Hi @nhe23 , thanks for filing this issue. 
I think it would be a good idea to implement such a feature. Would you like to go ahead and open a PR? 
As Go's built in `net/http` (which we are using) doesn't provide such a feature, we might want to use [hashicorp/go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) and provide the `RetryMax` parameter as an optional input parameter in `prometheus-msteams`. What do you think?

**Comment by nhe23** [comment]
@Knappek That sounds good. However I have minimal experience with golang and currently not much time. I could try implementing this but it would probably take a while...

**Comment by Knappek** [comment]
No worries, I will find some time next week to implement this.

**Comment by nhe23** [comment]
@Knappek I just had a look at the code and I think it should not be too hard to implement it myself. It is probably a good idea to have the retry configuration per configured channel. Then I would switch out the `net/http` server with the `hashicorp/go-retryablehttp` server as you suggested. The default `RetryMax` would be set to 0 and if a RetryMax value is set in the configfile this value would be used. 
Am I missing something? If not I would implement this the next few days.

**Comment by Knappek** [comment]
Awesome, looking forward to it! No I think that's it, unless I would set `retryMax` to a value greater 0, say 3?! Or is there any downside on this?

**Comment by nhe23** [comment]
Ok, then I'll set the default to 3 👍
