### ISSUE TITLE
[BUG] : Existing helm chart deployment template doesn't support multiple annotations.

### ISSUE THREAD

**Issue by pkd809** [prometheus-msteams/prometheus-msteams#183]
**Describe the bug**
helm release failed for Prometheus-msteams release. (error - "YAML parse error on prometheus-msteams/templates/deployment.yaml: error converting YAML to JSON: yaml: line 22: did not find expected key")

I found, Existing helm chart (Prometheus-msteam) deployment template doesn't support multiple annotations.

I have tested by modifying template it was working. (existing template - https://github.com/prometheus-msteams/helm-chart/blob/master/prometheus-msteams/templates/deployment.yaml#L21)

Made changes(working for multiple annotations) 

{{- if $.Values.podAnnotations }}      
       annotations:
{{ toYaml $.Values.podAnnotations | indent 8 }}
{{- end }}

**Version**
The docker image or release version of prometheus-msteams. 0.4.3  (Doesn't work with updated version as well)

**To Reproduce**
I have tested by modifying template it was working. (existing template - https://github.com/prometheus-msteams/helm-chart/blob/master/prometheus-msteams/templates/deployment.yaml#L21)

**Expected behavior**
A clear and concise description of what you expected to happen. Provide logs, metrics or traces if possible.

**Screenshots**

**Additional context**

**Comment by Knappek** [comment]
Good catch @pkd809! Thanks for filing this, I have created a PR that should fixes this. Would be great if you can review it and leave a comment.
