### ISSUE TITLE
[BUG] coalesce.go:160: warning: skipped value for extraEnvs: Not a table.

### ISSUE THREAD

**Issue by wrahmann** [prometheus-msteams/prometheus-msteams#188]
**Describe the bug**
I have defne proxy config in values.yaml under extraEnvs. However, when I run the helm chart I get the following error:

**coalesce.go:160: warning: skipped value for extraEnvs: Not a table.**
Release "prometheus-msteams" has been upgraded. Happy Helming!
NAME: prometheus-msteams
LAST DEPLOYED: Fri Mar  5 21:30:46 2021
NAMESPACE: monitoring
STATUS: deployed
REVISION: 8
TEST SUITE: None
NOTES:

**Version**
prometheus-msteams-1.1.1.tgz 

**To Reproduce**
Just define the proxy setting like this:

**extraEnvs:

  HTTP_PROXY: http://senp-prod-XXX.com:3128
  HTTPS_PROXY: http://senp-prod-XXX.com:3128**

**Expected behavior**
extraEnv shall be recognized and imported successfully.

**Additional context**
 I have seen some correction were committed related to this message but it seems it is not working. Please provide any workaround if fix needs time.  

https://github.com/prometheus-msteams/prometheus-msteams/pull/169

**Comment by Knappek** [comment]
this should be fixed with #169 , let me go ahead and merge it

**Comment by Knappek** [comment]
Released new chart that should fix this issue. Feel free to re-open if that is not the case. Thanks for reporting it!

**Comment by wrahmann** [comment]
thank you, the said error is not coming now.
