### ISSUE TITLE
Not able to start prometheus-msteams

### ISSUE THREAD

**Issue by dmarupov** [prometheus-msteams/prometheus-msteams#192]
This is more of a question or troubleshooting:

I have downloaded the source code from the releases page and after unzipping the source code I am not able to run the prometheus-msteams command.

I have tried to run the help command as follows:
`prometheus-msteams --help`

But this will return this:
`-bash: prometheus-msteams: command not found`

OR

`./prometheus-msteams --help`

But this will return this:
`-bash: ./prometheus-msteams: Is a directory`

I am using CentOS 7 and my golang version is as follows:
`go version go1.15.2 linux/amd64`

Also I tried to download prometheus-msteams-1.1.3.tgz, source code .zip and source code tar.gz. Same result with all three of them.

Am I missing something? Any help would be appreciated. Thank you.

**Comment by Knappek** [comment]
Hi @dmarupov , as `-bash: ./prometheus-msteams: Is a directory` states, it is a directory. Inside it, there should be the binary.

**Comment by dmarupov** [comment]
These are the contents of the directory:
![image](https://user-images.githubusercontent.com/46696879/111201017-556e2a00-8590-11eb-9da6-1f9c9ff2fd40.png)
Unfortunately, I don't see any bin subfolder or any binary files.

**Comment by Knappek** [comment]
Oh I see. This is the helm chart, here you can download the binary of the latest release: https://github.com/prometheus-msteams/prometheus-msteams/releases/tag/v1.4.2 . 

I could improve the readme to watch out for `vX.Y.Z` and **not** `prometheus-msteams-xxx`. Hope this helps!

**Comment by dmarupov** [comment]
@Knappek,

This worked beautifully. Thank you. Just an FYI for some reason I had to change the permission on the binary file but after that it was all good.

Thank you very much for your help.

**Comment by Knappek** [comment]
Yeah it's common that you have to change the permission/make it executable. Glad it works!
