### ISSUE TITLE
[Doubts] Rules for breaking messages in teams

### ISSUE THREAD

**Issue by DgoNascimento** [prometheus-msteams/prometheus-msteams#196]
Hello guys!

I would like support for the arrival of messages on MS Teams.

Note that the messages arrive, and some are not possible to read without clicking "see more".

Is it possible to change this setting?
Would it be on card.tmpl?

Thank you in advance.

**Comment by Knappek** [comment]
Hi @DgoNascimento , if I understand correctly, you would like to NOT have the "See more" button to expand very long MS teams messages, correct? 
If so, unfortunately this is not something that can be configured currently, please track [this open issue](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31544650-disabling-see-more?page=1&per_page=20).

**Comment by DgoNascimento** [comment]
Hi Knappek,

I really appreciate the information.

In addition, would you know if it is possible to prevent MS Teams from collecting alerts?

Receive one alert at a time?

I did a test removing the "group by", but without success.

Thank you in advance.

**Comment by Knappek** [comment]
@DgoNascimento promteams should not collect any alerts but send them separately. Can you please post the example where this does not seem to be the case? Also some description what you would like to have instead? Thanks!

**Comment by DgoNascimento** [comment]
Hi Knappek,

Verified that in the file alertmanager.yml we have the configuration of "group_by". In this case, it is configured like this:
group_by: ['alertname']

In this way, alerts are grouped into teams, by alertname.

![image](https://user-images.githubusercontent.com/78762621/113910982-d3001100-97af-11eb-9e91-0d98503a577e.png)


What I would like, is that there was no grouping, and that each alert was requested as a new message.
