### ISSUE TITLE
[Doubts] Forward alerts to a third channel, without filters

### ISSUE THREAD

**Issue by DgoNascimento** [prometheus-msteams/prometheus-msteams#197]
Hello guys!

I would like support for clarification of another doubt.

How could I send all alerts to a third channel, regardless of their criticality?

I tried that, but I get everything on channel_all.
...
  receiver: 'alert_channel_all'  # default/fallback request handler
  routes:
    - receiver: alert_channel_all
    - receiver: alert_channel_low
      match:
        severity: warning
    - receiver: alert_channel_high
      match:
        severity: critical

If I set it up like this, I don’t get paid on channel_all.
...
  receiver: 'alert_channel_all'  # default/fallback request handler
  routes:
    - receiver: alert_channel_low
      match:
        severity: warning
    - receiver: alert_channel_high
      match:
        severity: critical
    - receiver: alert_channel_all

Did they have any ideas?

Thank you in advance.

**Comment by Knappek** [comment]
Hi @DgoNascimento! I haven't fully understood what you are trying to do. Can you please describe a little bit more precise by mentioning:
- what you are trying to achieve
- how you try to achieve it
- what's the actual outcome
- what's the expected outcome

Please also use code blocks for the yaml snippets.

**Comment by DgoNascimento** [comment]
Hi Knappek,

what are you trying to achieve

I'm trying to get the alerts to be divided into different groups, but to be sent to another group, without any filter.

Imagine that we have a group without teams, that receives all alerts, another group that receives only warning alerts and another group that receives critical alerts.

how do you try to reach it

In the alertmanager.yml configuration we have the following

...
receiver: 'alert_channel_all' # default / fallback request handler
  routes:
    - receiver: alert_channel_low
      match:
        severity: warning
    - receiver: alert_channel_high
      match:
        severity: critical
...

In this way, I understand that the file is read from top to bottom and escapes when a condition is met. Since we have not set a route for alert_channel_all, it will not receive anything.

what is the real result

Creating a route to alert_channel_all, only he receives alerts of all criticisms

...
receiver: 'alert_channel_all' # default / fallback request handler
  routes:
    - receiver: alert_channel_low
      match:
        severity: [warning | critical]
    - receiver: alert_channel_low
      match:
        severity: warning
    - receiver: alert_channel_high
      match:
        severity: critical
...

In this way, alert_channel_all receives all alerts, while the others get nothing.

What is the expected result

I would then like all alerts to arrive at alert_channel_all, regardless of their criticality, and that the alert is also sent to the group corresponding to your criticism (alert_channel_high or alert_channel_low).
Thus, any alert would be sent to two groups:

Severity warning = alert_channel_all and alert_channel_low
Critical severity alert = alert_channel_all and alert_channel_high

**Comment by Knappek** [comment]
Got ya! Please follow [this detailed guide](https://www.robustperception.io/sending-alert-notifications-to-multiple-destinations), I think this will explain you how to achieve it. 
According to this guide, I think what you'd like to have is one receiver (`prometheus-msteams`) with multiple routes. Don't forget to set `continue` in the `alert_channel_all` as describe in the article.
Let me know if that helps.

**Comment by DgoNascimento** [comment]
Hi Knappek,

That was exactly it!

Thanks a lot for the help!!

Tks
