### ISSUE TITLE
Hostname from Hostmachine

### ISSUE THREAD

**Issue by marcown** [prometheus-msteams/prometheus-msteams#200]
Hi,

thanks for this great project!

I am using it in a docker-compose file together with prometheus and alertmanager.

Is there any way to display the hostname of the hostmachine in teams alerts?

Thanks!

**Comment by Knappek** [comment]
Hi @marcown sorry for the late reply. You could pass the hostname as an environment variable to the docker container and then use it in `prometheus-msteams`. 
Hope this helps!
