### ISSUE TITLE
[BUG] Missing recent binary releases

### ISSUE THREAD

**Issue by themanifold** [prometheus-msteams/prometheus-msteams#204]
**Missing binary releases**
We're missing the latest binary releases from the 'Releases' page. The latest one is v1.4.2 - since then, everything has been helm charts.

**Version**
Master branch

**To Reproduce**
Look at the releases page

**Expected behavior**
I expect the latest binary releases to be in the releases page

**Additional context**
I noticed this because I tried to use some of the newest features like the dynamic webhooks and found that v1.4.2 doesn't support them. What I did was then grab the binary from the latest official docker image, and confirmed that the dynamic webhook does work using that image.

https://github.com/prometheus-msteams/prometheus-msteams/actions/runs/419179943 <- here is the last time the github action was run, but the logs have expired since.

**Comment by Knappek** [comment]
thanks for reminding me @themanifold. There is an open PR #198 , I will try to get that merged soon and create a new release out of it.

**Comment by Knappek** [comment]
new release created
