### ISSUE TITLE
[BUG]Prometheus-msteams does not send alerts to msteams channel via proxy server

### ISSUE THREAD

**Issue by baraconguyen** [prometheus-msteams/prometheus-msteams#212]
- I used prometheus to send alerts to teams via a proxy server but no data is received.

error as follows:

`..../IncomingWebhook/e7e0714e1fb808a0589419bb75/21733118-bf94-4772-af1f-38caea159c3: dial tcp 52.98.40.66:443: i/o timeout
..../IncomingWebhook/e7e0363714e1fb808a0589419bb75/21733118-bf94-4772-af1f-38caea159c3: dial tcp 40.100.54.242:443: i/o timeout`

- I installed prometheus-msteams on centos 7 with a binary

- Please give me some advice, thank you

**Comment by Knappek** [comment]
@baraconguyen that's a duplicate to #101

**Comment by baraconguyen** [comment]
But i try setting up HTTP_PROXY or HTTPS_PROXY environment, it still get more error:

notify retry canceled after 2 attempts: Post \"http://localhost:2000/alert_channel\": context deadline exceeded"

**Comment by Knappek** [comment]
@baraconguyen sorry for being too fast in closing the issue.

Can you describe your infrastructure setup please?

**Comment by baraconguyen** [comment]
hi sir @Knappek , i set up prometheus-msteams on a linux with the binary via proxy outbout

> **My prometheus-msteams.service** 

`[Unit]
Description=Prometheus-msteams
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus-msteams
Group=prometheus-msteams
Type=simple
ExecStart=/usr/local/bin/prometheus-msteams -config-file /opt/prometheus-msteams/config.yml -template-file /opt/prometheus-msteams/card.tmpl

[Install]
WantedBy=multi-user.target`

 

> **my prometheus-msteams/config.yml**

`connectors:
  - alert_channel: "WEBHOOK URL"`

> **and the config alermanager.yml**

`global:
  http_config:
    proxy_url: 'http://(IP):3128'
  resolve_timeout: 5m

templates:
  - '/usr/local/bin/alertmanager/*.tmpl'

receivers:
- name: alert_channel
  webhook_configs:
  - url: 'http://localhost:2000/alert_channel'
    send_resolved: true

route:
  group_by: ['critical','severity']
  group_interval: 5m
  group_wait: 30s
  receiver: alert_channel
  repeat_interval: 3h`

**

> when i start prometheus.msteams, get the following error

`- Jun 10 20:53:20 prometheus-test alertmanager[961]: level=warn ts=2021-06-10T13:53:20.709Z caller=notify.go:723 component=dispatcher receiver=alert_channel integration=webhook[0] msg="Notify attempt failed, will retry later" attempts=14 err="unexpected status code 500: http://localhost:2000/alert_channel"

-  Post "http://localhost:2000/alert_channel\": context deadline exceeded"

`

**Comment by Knappek** [comment]
Can you please show me the content of `/opt/prometheus-msteams/config.yml` (**without** showing me the webhook url) pls?

**Comment by Knappek** [comment]
I assume, this is how `config.yaml` looks like?

```
connectors:
- alert_channel: "WEBHOOK URL"`
```

> Use three "`" backtip-quotes for code-formatting. It should look like this in order to get the above result:
![image](https://user-images.githubusercontent.com/18685317/121547607-926d7f80-ca0c-11eb-957c-e29728e035e0.png)

**Comment by baraconguyen** [comment]
hi sir @Knappek , my /opt/prometheus-msteams/config.yml

`connectors:
  - alert_channel: "https://......webhook.office.com/webhookb2/.....`

**Comment by baraconguyen** [comment]
![image](https://user-images.githubusercontent.com/85656213/121555700-6d453500-ca3d-11eb-872f-f84369d0251c.png)

my config.yaml

**Comment by baraconguyen** [comment]
i  tested with direct internet it work, but outbound proxy error:

>  level=error ts=2021-06-10T10:17:09.985Z caller=dispatch.go:310 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="alert_channel/webhook[0]: notify retry canceled after 2 attempts: Post \"http://localhost:2000/alert_channel\": context deadline exceeded"

**Comment by baraconguyen** [comment]
Seem alertmanager not send to prometheus-teams proxy on port 2000

>  alertmanager[1993]: level=error ts=2021-06-11T02:34:41.545Z caller=dispatch.go:310 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="alert_channel/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 403: http://localhost:2000/alert_channel"

**Comment by Knappek** [comment]
Yeah the error is in the alertmanager, not in prometheus-msteams. So it should be:
> Alertmanager --without-proxy--> prometheus-teams ---via-proxy--> MS Teams

Between Alertmanager and prometheus-msteams, you shouldn't require proxy settings, as they seem to run on the same system, don't they? 

You are trying to access prometheus-msteams from Alertmanager using `localhost`. Can you verify that you can reach prometheus-msteams via localhost from Alertmanager? HOw do you run Alertmanager, also as a systemd process?

**Comment by baraconguyen** [comment]
> Between Alertmanager and prometheus-msteams, you shouldn't require proxy settings, as they seem to run on the same system, don't they?
- Thanks sir @Knappek , yes they run on the same system. 

> Can you verify that you can reach prometheus-msteams via localhost from Alertmanager? 
---> No, i can't. Can you explain to me how to alertmanager reach prometheus-msteam  and prometheus-msteam go to Teams channel via proxy outbound or dns because i use proxy server to connect internet

> HOw do you run Alertmanager, also as a systemd process?
- yes, I run alertmanager as a systemd process

**Comment by Knappek** [comment]
you have to make sure that `alertmanager --> prometheus-msteams` does **not** use the proxy (which is presumably running on another host?!). If you export http proxy env variables on the linux host, it will also be picked up by Alertmanager. You can set `NO_PROXY` env variable for that.

**Comment by baraconguyen** [comment]
> you have to make sure that alertmanager --> prometheus-msteams does not use the proxy (which is presumably running on another host?!). If you export http proxy env variables on the linux host, it will also be picked up by Alertmanager. You can set NO_PROXY env variable for that.

- Thank for your supporting, 
-  Yeah, my proxy running on another host and i export http proxy env variables on the linux host.
- when i set NO_PROXY env variable, the alertmanger still get error: 

> ="unexpected status code 500: http://localhost:2000/alert_channel"

>  Post \"http://localhost:2000/alert_channel\": context deadline exceeded"

- and i want to ask how to config proxy for prometheus-msteams when i set no_proxy env variable

**Comment by baraconguyen** [comment]
> ./prometheus-msteams server \
>     -l localhost \
>     -p 2000 \
>     -w "Webhook of MS-teams channel"

l: On which address prometheus-msteams going to listen, the default address is “0.0.0.0” , "0.0.0.0" is a direct internet, how to config the address prometheus-msteams going to listen is the proxy

**Comment by Knappek** [comment]
Can you please log in to that Linux host and try to simluate a Prometheus Alert by sending a POST request directly to `prometheus-msteams` by [following these steps](https://github.com/prometheus-msteams/prometheus-msteams#simulating-a-prometheus-alerts-to-teams-channel)? With this you can easier debug and not rely on Prometheus Alertmanager to test the connection.
Can you please tell me how you've set `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` env variables?

**Comment by baraconguyen** [comment]
Dear sir, my setting env variables proxy 

> export http_proxy="http://ipserver:3128"
> export https_proxy="http://ipserver:3128"
> export no_proxy="127.0.0.1,localhost"
>

**Comment by baraconguyen** [comment]
I try to simluate a Prometheus alert by sending a POST request directly to prometheus-msteams and the information bellow.

>  curl -X POST -d @prom-alert.json http://localhost:2000/alert_channel

> [DEBUG] POST https://xxx.webhook.office.com/xxx

> [ERR] POST https://xxx.webhook.office.com/webhookb2/xx request failed: Post https://xx.webhook.office.com/webhookb2/xxx: dial tcp: lookup acbvn.webhook.office.com on [::1]:53: read udp [::1]:57232->[::1]:53: read: connection refused

**Comment by Knappek** [comment]
Your test shows that you can reach `prometheus-msteams`, but `prometheus-msteams` does not seem to reach your webhook URL. Next step would be to check whether you see incoming requests at the proxy.

**Comment by baraconguyen** [comment]
> Your test shows that you can reach `prometheus-msteams`, but `prometheus-msteams` does not seem to reach your webhook URL. Next step would be to check whether you see incoming requests at the proxy.

Thanks sir, i saw the prometheus-msteams reach but it doesn't post to webhook URL yet.  

i don't know how to check incoming request at the proxy

**Comment by baraconguyen** [comment]
Thanks sir for support, im very happy infor to you. I had fixed the problem successfull
- the problem: i must add the enviroment proxy in the service of prometheus-msteams ---> its work

**Comment by baraconguyen** [comment]
Thanks sir Knappek

**Comment by Knappek** [comment]
Great, glad it works now!
