### ISSUE TITLE
[FEATURE] Member tagging

### ISSUE THREAD

**Issue by chiaminchuang** [prometheus-msteams/prometheus-msteams#219]
Hello, 
Is it possible to tag members (ex: @eddie) through promteams to notify the specific members of a new alert related to them?
Thank you for your great project!!

**Comment by Knappek** [comment]
Hi @chiaminchuang you find information [here](https://answers.microsoft.com/en-us/msteams/forum/all/is-it-possible-to-tag-team-members-in-a-card/4218ef31-71ad-45e0-a478-43ef804ba714).

**Comment by chiaminchuang** [comment]
Thank you for your reply. It helps me a lot!!

**Comment by Knappek** [comment]
ICYMI, there is an open issue for Adaptive card support: #202 . If you'd like to contribute to this project, feel free to pick that issue :)
