### ISSUE TITLE
Openshift deployment does not work in other namespaces other than "Default" due to user 1000 

### ISSUE THREAD

**Issue by glennodickson** [prometheus-msteams/prometheus-msteams#232]
Hi

I've attempted to deploy this to another namespace other than "default" however, Openshift reports that the container is attempting to user 1000 which violates Openshift's security however, deploying to "default" works but is not ideal.

Do you have alternative approach to deploying to Openshift where it can support a namespace other than "Default" pls?

Thanks

**Comment by kbudde** [comment]
duplicate #233
