### ISSUE TITLE
Suddenly Getting Error  Response Message "1" on some alerts

### ISSUE THREAD

**Issue by heyoheyo** [prometheus-msteams/prometheus-msteams#234]
**Describe the bug**
Suddently getting:

`Nov 24 16:57:46 <SENSITIVE_HOST> ms-teams[xxxx]: {"caller":"logging.go:25","err":null,"level":"debug","response_message":"1","response_status":200,"ts":"2021-11-24T16:57:46.270343596Z","webhook_url":"<SENSITIVE_WEBHOOK_ADDRESS"}
`

**Version**
1.4.2

**To Reproduce**
Don't know

**Expected behavior**
I suddenly started getting the error above on just some of my alerts. I was previously able to get that alert into MSTeams without issues, it just suddenly stopped. Any idea what this could be?

**Comment by heyoheyo** [comment]
@Knappek - do you have any idea what this could be caused by? If there was an actual log entry, I would be able to debug and not bother, apologies :)

**Comment by Knappek** [comment]
@heyoheyo I have no idea. I think it's more suitable to file an issue at MS Teams as we can't deal with it and solely rely on the `response_status`.
