### ISSUE TITLE
[Security] Images have Vulnerabilitys

### ISSUE THREAD

**Issue by CoreDi** [prometheus-msteams/prometheus-msteams#236]
Image v1.4.2 has 1 Vulnerability:

![image](https://user-images.githubusercontent.com/32080303/143848421-b3c38eb8-f2f2-46af-bd5e-62a30f33d916.png)

Image v1.5.0 has 10 Vulnerabilitys:
![image](https://user-images.githubusercontent.com/32080303/143848530-7d088a65-3c8f-48ae-9006-918f7206cc40.png)

Is it possible to update the Images?

For now i´m using v1.4.2 which seems okay for now with 1 minor Vulnerability.
But a "clean" Image would be fine :) .

**Comment by tuxerrante** [comment]
Also the v1.5 should be updated

Scanned by anchore:
![image](https://user-images.githubusercontent.com/8364469/147643501-6071fd32-f24a-49b6-8c61-a92d79402372.png)
