### ISSUE TITLE
!! Additional Maintainers wanted !!

### ISSUE THREAD

**Issue by Knappek** [prometheus-msteams/prometheus-msteams#237]
This project used to be a project with very good response times from the maintainers @Knappek and @bzon. Unfortunately we can't keep up with that and therefore we are searching for more active Collaborators and Maintainers.

Anybody interested in Kubernetes, Prometheus and Alerting is a good candidate. There is no need to be an expert in any of those technologies though, neither on Go or with the MS Teams API. The best way to learn new technologies is by maintaining real world open source projects like this one.

We would like to encourage anybody interested in raising their hands and keep this project maintained and awesome ❤️

**Comment by Knappek** [comment]
@kbudde, @ckotzbauer, @fischerman you did some great contributions to this project. Is any of you interested?

**Comment by kbudde** [comment]
Interested? This sounds like a lot of work to me. 

@Knappek  🆗, I'm in.

**Comment by Knappek** [comment]
@amimof are you also interested?

**Comment by Knappek** [comment]
@kbudde awesome, that's great news! And thanks for this quick reply. It's actually not a lot of work, unless you want to refactor the code ;) (which you can if you think it's a good idea)

**Comment by Knappek** [comment]
@kbudde I am thinking about how we can easy collaborate if there's a need to. Both @bzon and I are on the Kubernetes slack channel, so you can reach out to us if you want to discuss certain things.

**Comment by ckotzbauer** [comment]
I'm also interested generally but I can't ensure that I can always respond quickly. 😉

**Comment by Knappek** [comment]
That's fine @ckotzbauer, the more maintainers we have, the more we can spread ownership :). Thank you very much for your support, much appreciated!

**Comment by amimof** [comment]
@Knappek I’d love to be a maintainer however currently i just don’t have enough bandwidth. Once I do I’ll give you a ping 😉

**Comment by Knappek** [comment]
Sounds good @amimof
