### ISSUE TITLE
[BUG] 404 cant install using helm

### ISSUE THREAD

**Issue by naddame** [prometheus-msteams/prometheus-msteams#240]
The link https://prometheus-msteams.github.io/prometheus-msteams/ is not reachable. We get 404 when we try installing prometheus-msteams using helm

**Comment by dbluxo** [comment]
A few days ago the URL was accessible and I was able to pull the Helm Chart...

**Comment by ckotzbauer** [comment]
@naddame Does only https://prometheus-msteams.github.io/ return a 404 or https://prometheus-msteams.github.io/index.yaml too?
There is no index.html deployed at github-pages, so the first URL should always return 404

**Comment by naddame** [comment]
@ckotzbauer Both return 404

**Comment by ckotzbauer** [comment]
I opened the link with my browser and tested the helm command just before writing the comment. Now from my tablet I also get a 404....

**Comment by ckotzbauer** [comment]
I posted the wrong yaml link. The correct one: https://prometheus-msteams.github.io/prometheus-msteams/index.yaml

**Comment by Knappek** [comment]
@naddame there shouldn't be need to open the link on the browser. You can simply use the helm cli:

```
# add repo, according to the docs: https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/README.md
helm repo add prometheus-msteams https://prometheus-msteams.github.io/prometheus-msteams/

# list latest release
helm search repo prometheus-msteams

# list all releases
helm search repo prometheus-msteams -l
```

Hope this helps.
