### ISSUE TITLE
Notification are not getting triggered to MS Teams

### ISSUE THREAD

**Issue by srikanthankam** [prometheus-msteams/prometheus-msteams#253]
**Describe the bug**
I installed prometheus-msteams using helm by following the steps provided in this Github.
For Prometheus-Grafana, I installed using helm (kube-promethues-stack)

**Expected behavior**
I thought alerts will be received on Teams channel I created, but not received

-----------config.yaml----------------

<img width="739" alt="image" src="https://user-images.githubusercontent.com/84887392/171139816-cb4ed0e1-2661-46c0-8686-7bce0f371667.png">

------------------------------------------------------
Can anyone please suggest is there any thing I am missing?

**Comment by Knappek** [comment]
HI @srikanthankam , can you give us the alertmanager config, especially how you've configured `receivers`. And please provide the logs of `prometheus-msteams`.

**Comment by LionHuntDiG** [comment]
hi 
I'm also facing same issue.

Here are the logs of prometheus-msteams pod.
{"caller":"transport.go:39","level":"debug","request_path_added":"alertmanager-warning","ts":"2022-08-14T17:42:17.828339959Z"}
{"caller":"transport.go:39","level":"debug","request_path_added":"alertmanager-critical","ts":"2022-08-14T17:42:17.92784166Z"}
{"caller":"transport.go:43","level":"debug","request_path_added":"/_dynamicwebhook/*","ts":"2022-08-14T17:42:17.927919365Z"}
{"branch":"HEAD","build_date":"2022-08-06T12:02:22+0000","caller":"main.go:364","commit":"412ff33","listen_http_addr":":2000","ts":"2022-08-14T17:42:17.928164419Z","version":"v1.5.1"}
^C

**Comment by LionHuntDiG** [comment]
its working for me.

**Comment by Knappek** [comment]
@LionHuntDiG can you please describe what hasn't worked for you and how you fixed it pls?

**Comment by LionHuntDiG** [comment]
there was some mistakes in my alertmanager.yaml config, i rectified those,  and i started receiving notifications on teams...
