### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Breee** [prometheus-msteams/prometheus-msteams#254]
Is this project still maintained?

**Comment by kbudde** [comment]
Why are you asking?

**Comment by srl295** [comment]
First, thanks for this project.

> Why are you asking?

I didn't write that, but I do note that docker images on quay.io have not been updated to fix security issues (#241, #245)

**Comment by CoreDi** [comment]
As already stated, no (Security) updates since month.
Nice Project, but sadly we can't use this, especially for production Clusters. :( 
So we are looking for other solutions.

**Comment by Breee** [comment]
We could fork and use renovate with automerges. Or we actually bring this
functionality into alertmanager itself.

CoreDi ***@***.***> schrieb am Di., 26. Juli 2022, 23:47:

**Comment by kbudde** [comment]
The Docker container is already switched to scratch, that should solve 99% of the problems. 
Only the release is currently missing. 

I will see that the libraries used are updated as well.

You are right that not enough time is invested in the project.

Security holes and regular updates are feasible. I will take care of it.

**Comment by kbudde** [comment]
@Knappek, @bzon  I need your help otherwise we should close this repository.
It seems like the creation of docker images is done outside of github workflows -> I have no access.

- [ ] Create new docker image with tag v1.5.1
- [ ] Retrigger https://github.com/prometheus-msteams/prometheus-msteams/pull/216
- [ ] Merge https://github.com/prometheus-msteams/prometheus-msteams/pull/216

**Comment by zhan9san** [comment]
Thanks for your contribution on this project.

> otherwise we should close this repository.

Please keep it open. I can help on CICD stuff if you don't mind to grant me permissions.

**Comment by kbudde** [comment]
@zhan9san I don't have the permissions as well 😢 

@Knappek was looking for additional maintainers some time ago. I wanted to help but unfortunately I was lacking the time and just did nothing.
I'm still limited in time but applying dependency updates / ensure that security patches are applied in time is something I can do for sure.
I only need enough permissions.

**Comment by Knappek** [comment]
@kbudde I have assigned you admin permissions. 

I am sorry that you all have the feeling this project is not maintained anymore. I am happy to add collaborators to make this project active again. 

@zhan9san thanks for your support, I'll add you as a collaborator 👍

**Comment by kbudde** [comment]
@Knappek Thank you. Will do my best.
The first thing we have to do is to create a docker image on quay.io.
Can you add the credentials for quay.io for this project. We can then automate the deployment of docker images.

**Comment by Knappek** [comment]
@kbudde thanks for all your efforts. I have stored the secrets in the [settings](https://github.com/prometheus-msteams/prometheus-msteams/settings/secrets/actions). Is that sufficient? I think I can always give you admin permissions on the quay.io org if needed.

**Comment by Knappek** [comment]
Thanks everyone here for support! I really appreciate that ❤️ . 
And again sorry for not being very active in the past but I have lots of personal things going on and limited time to solo maintain this project. But I will do my best to support all of you and collaborators to keep this project alive ✌️

**Comment by kbudde** [comment]
New version was released. 
At least three people are working on this repository.

Feel free to open a new issue if you think some important issues are missed.
