### ISSUE TITLE
[BUILD] Automatic dependency updates

### ISSUE THREAD

**Issue by kbudde** [prometheus-msteams/prometheus-msteams#258]
There are currently several different dependencies in prometheus-msteams: github actions, go libraries and docker.
Keeping all of them up to date is tedious.

Having a tool like [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) or [renovate](https://docs.renovatebot.com/)  simplifies this process.

For the github actions it would be worth considering using the commit hash instead of a version number. This ensures that all builds remain reproducible. Go offers similar functionality by default via go.sum.
Renovate supports this for github-actions([doc](https://docs.renovatebot.com/modules/manager/github-actions/#additional-information)). Not sure about dependabot.

**Comment by ckotzbauer** [comment]
👍 for Renovate (better configurable than dependabot)

**Comment by kbudde** [comment]
OK, sound like renovate.
We should also run the tests in our pipelines to ensure that nothing is breaking. There are some outdated packages.

**Comment by zhan9san** [comment]
It is fixed in #283
