### ISSUE TITLE
[BUG] OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by Wally110** [prometheus-msteams/prometheus-msteams#261]
**Describe the bug**
"/bin/sh: no such file or directory" occurred as I just pulled the image of latest version (v1.5.1) and tried to docker exec into it.
There is not such an issue for v1.5.0.
Don't know if this is a bug.

**Version**
latest version (v1.5.1)

**To Reproduce**
pull it  and docker exec into it 

**Expected behavior**
Able to enter container.

**Screenshots**
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/18901936/187147933-1e852a7d-8978-4d18-a053-515c1e644aac.png">

**Comment by ckotzbauer** [comment]
Hi @Wally110,
the base-image was changed to scratch in 1.5.1, so there's no shell anymore as part of the image. Why do you need this?

**Comment by Wally110** [comment]
Oh, I just wanted to enter containers to debugging few things, such as if custom message card works well. No big deal. May I ask why you removed shell support, except to reduce image size?

**Comment by ckotzbauer** [comment]
Mainly to reduce the CVEs and the attack surface

**Comment by Wally110** [comment]
I see. No further questions. Thank you!
