### ISSUE TITLE
[BUG] Listening port hardcoded??

### ISSUE THREAD

**Issue by felicianmv** [prometheus-msteams/prometheus-msteams#281]
**Describe the bug**
I wanted to change container/service port for my deployment, for that I added 
```
container:
  port: 8080
  additionalArgs: []

service:
  type: ClusterIP
  port: 8080
```
into config file.
But when I checked the logs:

```
{"caller":"transport.go:39","level":"debug","request_path_added":"msteams","ts":"2022-12-21T16:21:05.999627552Z"}
{"caller":"transport.go:43","level":"debug","request_path_added":"/_dynamicwebhook/*","ts":"2022-12-21T16:21:06.005879896Z"}
{"branch":"HEAD","build_date":"2022-08-06T12:02:22+0000","caller":"main.go:364","commit":"412ff33","listen_http_addr":":2000","ts":"2022-12-21T16:21:06.006025203Z","version":"v1.5.1"}
```

**Version**
1.5.1

**To Reproduce**
added the above lines into config file and deploy helm chart

**Expected behavior**
A clear and concise description of what you expected to happen. Provide logs, metrics or traces if possible.

**Screenshots**

**Additional context**

**Comment by zhan9san** [comment]
Hi @felicianmv 

IMHO, there is no need to change container port if you want to access the service on a different port.

You can just change the service port as below.

```
$ cat config.yaml
service:
  type: ClusterIP
  port: 8080
  targetPort: 2000
```

```shell
helm upgrade --install prometheus-msteams -f config.yaml prometheus-msteams/prometheus-msteams
```

What I tested shows it's `8080` as expected.

```shell
$ kubectl get svc prometheus-msteams
NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
prometheus-msteams   ClusterIP   10.106.154.172   <none>        8080/TCP   12m
```

The `container.port` in value file will change `containerPort` in podSpec, but it won't change the listening port.

BTW, changing listening port can be supported to add args in podSpec, if you want to submit a PR to fix it.

Reference: https://stackoverflow.com/questions/57197095/why-do-we-need-a-port-containerport-in-a-kuberntes-deployment-container-definiti
