### ISSUE TITLE
[BUG] Helm repo no longer working

### ISSUE THREAD

**Issue by mihaico** [prometheus-msteams/prometheus-msteams#291]
**Describe the bug**
Helm repo link is no longer working https://prometheus-msteams.github.io/prometheus-msteams/

https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/README.md?plain=1#L21

**Comment by zhan9san** [comment]
Hi @mihaico 

Did you encounter any issues here?

After you run `helm repo add prometheus-msteams https://prometheus-msteams.github.io/prometheus-msteams/`, the repo is added.

And you can get it by `helm repo list`.


`https://prometheus-msteams.github.io/prometheus-msteams/` is returned 404 is expected. In the contrast, 
`https://prometheus-msteams.github.io/prometheus-msteams/index.yaml` is working.

**Comment by mihaico** [comment]
Thanks @zhan9san , I should have given more context.

My usecase was around provisioning a flux HelmRepository which complains that:
```
failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://prometheus-msteams.github.io/prometheus-msteams/index.yaml"
```
, which does not happen for the case of e.g.  ```https://grafana.github.io/helm-charts```

Anyways I am using a local repo, but I thought it might help others.

**Comment by zhan9san** [comment]
I tried it locally, and it works well.

Would you mind showing me how to reproduce this issue?

Firstly, I suspect it's network issue, but you said it works for grafana repo.

**Comment by mihaico** [comment]
After some more digging, I found it is indeed a networking issue ```tls: server chose an unconfigured cipher suite```. As it can be solved via a local config issue, this issue can be closed .
Thanks
