### ISSUE TITLE
Direct integration into Alertmanager?

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-msteams/prometheus-msteams#316]
:wave: Alertmanager maintainer here.
We've been asked many times for a native integration of MSTeams in Alertmanager (https://github.com/prometheus/alertmanager/issues/3076 is the latest request). Is there an interest from this project to contribute their implementation directly into https://github.com/prometheus/alertmanager? Assuming that the people here agree to support the integration in the long run, I'd be ok to sponsor this effort.

cc @gotjosh

**Comment by kbudde** [comment]
Hi @simonpasquier,

For me this sounds really interesting. This should solve some integration issues we had in the past. But I would like to hear the opinion of all maintainers.

@bzon , @Knappek , @ckotzbauer , @zhan9san ?

**Comment by zhan9san** [comment]
LGTM

**Comment by Knappek** [comment]
Sounds reasonable considering the amount of people/companies using MS teams.

**Comment by kbudde** [comment]
I think we have a decision.
PR is already pending: https://github.com/prometheus/alertmanager/pull/3324

**Comment by gotjosh** [comment]
I think we can close this now.
