### ISSUE TITLE
Description field is used as header

### ISSUE THREAD

**Issue by byteSamurai** [prometheus-msteams/prometheus-msteams#61]
We are using the `description` field also for instruction how to get rid of the error for 1st and 2nd level support. Wouldn't it be better to use the `summary` field as head line instead of the description field.

For e.g. in your screenshot:

![image](https://user-images.githubusercontent.com/6654064/66053468-ad4ad980-e532-11e9-90a0-48e0c96eef64.png)

This would mean, the summary text is used for the link. So the anker text would be: "Server High Memory Usage"

To streamline this a bit more we could drop the summary field in the list below.

Would you accept a PR with this?

**Comment by Knappek** [comment]
You can easily do this by adapting the message card default template. See this docs how to use your own template: https://github.com/bzon/prometheus-msteams#customise-messages-to-ms-teams

**Comment by byteSamurai** [comment]
I know, but I consider the default not as a good approach. Change would be quite easy, so can we change it? 

So if you would accept a PR here... :yum:

**Comment by Knappek** [comment]
Haha now i get it 😃. Hmm tbh I don't care but this change would mean a major change which is not backwards compatible. @bzon what are your thoughts?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by byteSamurai** [comment]
Just stumbled upon another optimization: Alertnames within teams should contain "release" or "firering like in mail subject, so one can see in the activity feed (not only in the channel) which alert is still active.

**Comment by Knappek** [comment]
agree, that's a very good idea. Is this actually possible? On Teams for Mac I can only see that there is a new message, but I don't see the title or anything in the activity feed.
This is how it looks to me:
![image](https://user-images.githubusercontent.com/18685317/67040318-8809be00-f123-11e9-9c39-d6dc77fc1ed4.png)

**Comment by Knappek** [comment]
oooh, got it, you mean the feed in teams. Okay, I can see the summary there. I think a PR on that will be accepted ;)

**Comment by byteSamurai** [comment]
Very nice, will send it in Saturday. Thx in advance

**Comment by Knappek** [comment]
@byteSamurai do you still plan to implement this?
