### ISSUE TITLE
Fingerprint unavailable

### ISSUE THREAD

**Issue by Josephine24** [prometheus-msteams/prometheus-msteams#81]
Fingerprint is now sent as part of the JSON payload from Alertmanager. I am not sure if this is added in the code cause when i tried to get Fingerprint in the template, I couldn't fetch the information. Whereas I am able to do the same for slack.

**Comment by Knappek** [comment]
Hi @Josephine24, in theory it should be possible to extract it by modifying the template. Can you pls elaborate a little what and how you've tried it? What results you got and what you'd expect? Thanks.

**Comment by Josephine24** [comment]
Hi @Knappek, I tried fetching the Fingerprint in the card.tmpl but I'm getting error as shown below:
time="2020-01-10T09:13:51Z" level=error msg="failed to template alerts: template: card.tmpl:25:150: executing \"teams.card\" at <.Fingerprint>: can't evaluate field Fingerprint in type template.Alert"

I added {{.Fingerprint}} to fetch it as we do in alertmanager slack template. It works in slack but not in Teams. If I am missing something let me know. Thank you

**Comment by Knappek** [comment]
Can you please post your entire card.tmpl?

**Comment by Josephine24** [comment]
{{ define "teams.card" }}
{
  "@type": "AdaptiveCard",
  "@context": "http://schema.org/extensions",
  "themeColor": "{{- if eq .Status "resolved" -}}2DC72D
                 {{- else if eq .Status "firing" -}}
                    {{- if eq .CommonLabels.severity "critical" -}}E61414
                    {{- else if eq .CommonLabels.severity "major" -}}D5CC00
                    {{- else if eq .CommonLabels.severity "info" -}}007CD5
                    {{- else -}}808080{{- end -}}
                 {{- else -}}808080{{- end -}}",
  "summary": "{{- if eq .CommonAnnotations.summary "" -}}
                  {{- if eq .CommonAnnotations.message "" -}}
                    {{- .CommonLabels.alertname -}}
                  {{- else -}}
                    {{- .CommonAnnotations.message -}}
                  {{- end -}}
              {{- else -}}
                  {{- .CommonAnnotations.summary -}}
              {{- end -}}",
  "title": "{{ if gt (.Alerts.Firing | len) 0 }}[FIRING: {{ .Alerts.Firing | len }}] {{ end }}{{ if gt (.Alerts.Resolved | len) 0 }} [RESOLVED: {{ .Alerts.Resolved | len }}] {{ end }} {{ .GroupLabels.alertname }} ({{ .CommonLabels.severity }}) ({{ .Status }})",
  "sections": [ {{$externalUrl := .ExternalURL}}
  {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
    {
      "activityTitle": "[{{ $alert.Annotations.summary }}](https://<my-link>/#{{ .Labels.alertname }}/#**{{.Fingerprint}}**)",
      "facts": [
        {
          "name": "**Alertsrc**",
          "value": "{{ .Labels.alert }}"
        },
        {
          "name": "**Site**",
          "value": "{{ .Labels.site }}"
        }

      ],
      "markdown": true
    }
    {{- end }}
  ]
}
{{ end }}

**Comment by Josephine24** [comment]
@Knappek Posted the card.tmpl above. I have tried to fetch the {{.Fingerprint}} in activityTitle

**Comment by Knappek** [comment]
Hi @Josephine24, thanks for providing the details. I need to investigate by my own, I'll keep you posted.

**Comment by Knappek** [comment]
Hi @Josephine24, not yet, didn't have time yet to test, currently lots of stuff to do for work. I'll try to have a look into it on the weekend. I'm sorry for that.

**Comment by Josephine24** [comment]
@Knappek that's ok. No Probs. I am using this in one of my project where i have to use this Fingerprint for sure. Once you let me know i can use it. :)

**Comment by bzon** [comment]
@Josephine24 can you try using the latest release v1.2.1? It uses JSON structured logging by default which includes the payload from Alertmanager. If you manage to recreate the issue, please provide us the logs.

**Comment by Josephine24** [comment]
Hi @bzon, I tried with the latest image and still facing the same issue. I am using the template that i have placed earlier. I tried with both {{.Fingerprint}} and {{ .fingerprint }}.

time="2020-02-06T09:18:02Z" level=error msg="failed to template alerts: template: card.tmpl:25:148: executing \"teams.card\" at <.Fingerprint>: can't evaluate field Fingerprint in type template.Alert"

**Comment by bzon** [comment]
@Josephine24 are you using docker or kubernetes? The latest version is v1.3.2. The logs are formatted in JSON. The logs you presented are from an older version. Please check the release page.

**Comment by bzon** [comment]
`docker pull quay.io/prometheusmsteams/prometheus-msteams:v1.3.2`

**Comment by Josephine24** [comment]
I will check on this and update if i am able to get the fingerprint. I am using both Docker and Kubernetes. Two different servers.

**Comment by Josephine24** [comment]
Thank you @bzon. It worked for Docker. Will check for K8s and let you know if it works fine 👍

**Comment by bzon** [comment]
@Josephine24 sure. Please close the issue if everything works ok. 👍
