### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by choppedpork** [prometheus-msteams/prometheus-msteams#86]
Hello!

First of all - thanks for prometheus-msteams, since my company has unfortunately decided to move to Teams from Slack it's been indispensable!

We have (twice now) noticed that sometimes prometheus-msteams starts using a _little bit_ too much memory for what it does. The second time it happened we captured the following via `docker stats`:
![image](https://user-images.githubusercontent.com/11997044/73466428-c6955280-4379-11ea-8ab2-10be075218d1.png)
(apologies for image instead of text - it wasn't me collecting the data, the columns are: container id, name, cpu %, mem usage / limit, mem %, net i/o, block i/o, pids)

The interesting this is that after a restart, memory usage grows quite quickly and gets into a pickle again - suggesting this is not a result of some state within the application but rather of either the data in prometheus, our card template or responses from Teams. I'm running on the assumption that CPU usage here would be the garbage collector rather than something in the application itself but that's just an assumption. There's been a couple of alerts in alertmanager at the time (iirc) and silencing them did not resolve the issue - we still have that one instance exhibiting what looks like a memory leak. A restart does not seem to help either so I should be in a position to gather some more data to help diagnose this - anything you would find helpful? This is version 1.1.4 by the way - we're going to roll out an update to 1.1.5 (and add a memory limit... 😃) soon but can keep that one troublesome instance in it's current state for a while if that helps.

**Comment by choppedpork** [comment]
A small update - following silencing of the alerts we've added a memory limit of 1024m and restarted, after a couple of OOMs the situation seems to have magically resolved itself (so might no longer be able provide some information, unfortunately). Here's some screengrabs of memory usage over the past 6h and 24h respectively:
![Screenshot 2020-01-30 at 17 00 01](https://user-images.githubusercontent.com/11997044/73471997-3e677b00-4382-11ea-9aae-94ebe4bdec3d.png)
![Screenshot 2020-01-30 at 16 42 36](https://user-images.githubusercontent.com/11997044/73471014-a2893f80-4380-11ea-8cb2-23d424e76473.png)

**Comment by bzon** [comment]
Hmm.. interesting. This is not usual. Do you know how many alerts are firing to Teams? My guess is there is too much alerts buffered in memory waiting to be sent to Microsoft Teams. 

On the other note, I’m currently doing a refactor of code on a separate branch which adds metrics to see how many requests and connections the app currently serves. It’s also an overall code optimisation.

**Comment by bzon** [comment]
@choppedpork can you try using the **latest** tagged image? It is a release candidate for #87.

If the problem persists, can you send the output of the http request from `/debug/pprof/goroutine` while the memory usage is high.

**Comment by choppedpork** [comment]
Thanks @bzon - I saw #87 before raising this issue and quite excited about the instrumentation (always good to have this data for cases like this very one!). 

As we've only since this twice (over the course of ~6 months I believe) and now have a memory limit in place what I might do is wait until the release and then ensure we've got scraping et al configured - we do have a dozen or so of these deployed - as well as a runbook in case someone hits this so that we're ready to gather all the data should this happen again.

**Comment by bzon** [comment]
@choppedpork the escaping was introduced in v1.2.0 and the latest now is v1.2.1 which is also available in helm.

Is it going to be a big effort to change the templating? We can probably think of a solution to bring it back to the previous way. Cc @Knappek

**Comment by bzon** [comment]
@choppedpork please test the release v1.3.0, we made the auto escape configurable.

https://github.com/bzon/prometheus-msteams/releases/tag/v1.3.0

**Comment by choppedpork** [comment]
@bzon thanks! you seem to be releasing at a nearly impossible to keep up with pace, it feels like I barely had time to sneeze and we're 5 releases out of date already!
We'll be rolling out the latest 1.3.x version next week together with prometheus configs to ensure we've got metrics captured as well. I'm not sure if it even makes sense to keep this issue open considering the rewrite and how infrequent of an issue this is - feel free to close if you think it's just unnecessary clutter.

**Comment by bzon** [comment]
> you seem to be releasing at a nearly impossible to keep up with pace, it feels like I barely had time to sneeze and we're 5 releases out of date already!

I did everything I could. 😃
